-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-22T22:17:04
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

CREATE TABLE IF NOT EXISTS item_template_backup_budget_normalizer_20260622_221703 AS
SELECT *
FROM item_template
WHERE entry IN (35870, 39221, 49120, 47934, 48007, 50802);

-- 35870 Stoneground Cleaver
UPDATE item_template
SET
  stat_value1 = 72
WHERE entry = 35870;

-- 39221 Wraith Spear
UPDATE item_template
SET
  stat_value1 = 78,
  stat_value2 = 68,
  stat_value3 = 59,
  stat_value4 = 39
WHERE entry = 39221;

-- 49120 Direbrew's Bloody Shanker
UPDATE item_template
SET
  stat_value2 = 33,
  stat_value3 = 33,
  stat_value4 = 23,
  stat_value5 = 19
WHERE entry = 49120;

-- 47934 Planestalker Signet
UPDATE item_template
SET
  stat_value1 = 60,
  stat_value2 = 66,
  stat_value3 = 37,
  stat_value4 = 37,
  stat_value5 = 98
WHERE entry = 47934;

-- 48007 Planestalker Band
UPDATE item_template
SET
  stat_value1 = 60,
  stat_value2 = 66,
  stat_value3 = 37,
  stat_value4 = 37,
  stat_value5 = 98
WHERE entry = 48007;

-- 50802 Gargoyle Spit Bracers
UPDATE item_template
SET
  armor = 1082
WHERE entry = 50802;

-- ITEM BUDGET NORMALIZER END
