-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-22T22:14:29
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

-- 35870 Stoneground Cleaver
UPDATE item_template
SET
  stat_value1 = 61
WHERE entry = 35870;

-- 39221 Wraith Spear
UPDATE item_template
SET
  stat_value1 = 90,
  stat_value2 = 79,
  stat_value3 = 68,
  stat_value4 = 45
WHERE entry = 39221;

-- 49120 Direbrew's Bloody Shanker
UPDATE item_template
SET
  stat_value2 = 38,
  stat_value3 = 38,
  stat_value4 = 27,
  stat_value5 = 22
WHERE entry = 49120;

-- 47934 Planestalker Signet
UPDATE item_template
SET
  stat_value1 = 70,
  stat_value2 = 77,
  stat_value3 = 44,
  stat_value4 = 44,
  stat_value5 = 115
WHERE entry = 47934;

-- 48007 Planestalker Band
UPDATE item_template
SET
  stat_value1 = 70,
  stat_value2 = 77,
  stat_value3 = 44,
  stat_value4 = 44,
  stat_value5 = 115
WHERE entry = 48007;

-- 50802 Gargoyle Spit Bracers
UPDATE item_template
SET
  armor = 1735
WHERE entry = 50802;

-- ITEM BUDGET NORMALIZER END
