-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-22T20:31:54
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

-- 1917 Jeweled Dagger
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 11
WHERE entry = 1917;

-- 18957 Brushwood Blade
UPDATE item_template
SET
  dmg_min1 = 11,
  dmg_max1 = 21
WHERE entry = 18957;

-- 23430 Mercenary Sword
UPDATE item_template
SET
  dmg_min1 = 9,
  dmg_max1 = 17
WHERE entry = 23430;

-- 23431 Mercenary Stiletto
UPDATE item_template
SET
  dmg_min1 = 5,
  dmg_max1 = 11
WHERE entry = 23431;

-- 816 Small Hand Blade
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 12
WHERE entry = 816;

-- 3223 Frostmane Scepter
UPDATE item_template
SET
  dmg_min1 = 9,
  dmg_max1 = 17
WHERE entry = 3223;

-- 4947 Jagged Dagger
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 12
WHERE entry = 4947;

-- 4948 Stinging Mace
UPDATE item_template
SET
  dmg_min1 = 9,
  dmg_max1 = 18
WHERE entry = 4948;

-- 24339 Stung
UPDATE item_template
SET
  dmg_min1 = 10,
  dmg_max1 = 20
WHERE entry = 24339;

-- 26049 Old Elekk Prod
UPDATE item_template
SET
  dmg_min1 = 7,
  dmg_max1 = 14
WHERE entry = 26049;

-- 26053 Elekk Handler's Blade
UPDATE item_template
SET
  dmg_min1 = 8,
  dmg_max1 = 16
WHERE entry = 26053;

-- 33791 Heavy Copper Longsword
UPDATE item_template
SET
  dmg_min1 = 10,
  dmg_max1 = 20
WHERE entry = 33791;

-- 4303 Cranial Thumper
UPDATE item_template
SET
  dmg_min1 = 12,
  dmg_max1 = 24
WHERE entry = 4303;

-- 4974 Compact Fighting Knife
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 13
WHERE entry = 4974;

-- 23403 Salvaged Mail Leggings
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 23403;

-- 3586 Logsplitter
UPDATE item_template
SET
  dmg_min1 = 31,
  dmg_max1 = 47
WHERE entry = 3586;

-- 14363 Deprecated Runic Cloth Pants
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 14363;

-- 26030 Jessera's Fungus Lined Hauberk
UPDATE item_template
SET
  armor = 181
WHERE entry = 26030;

-- 1405 Foamspittle Staff
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1405;

-- 3154 Thelsamar Axe
UPDATE item_template
SET
  dmg_min1 = 13,
  dmg_max1 = 25
WHERE entry = 3154;

-- 5780 Murloc Scale Belt
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 5780;

-- 6186 Trogg Slicer
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 6186;

-- 6243 Green Woolen Robe
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value2 = 3,
  stat_value3 = 2
WHERE entry = 6243;

-- 7738 Evergreen Gloves
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 7738;

-- 10919 Apothecary Gloves
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 10919;

-- 14150 Robe of Evocation
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 14150;

-- 65492 Broadsword of the Crown
UPDATE item_template
SET
  dmg_min1 = 18,
  dmg_max1 = 41.05
WHERE entry = 65492;

-- 3487 Heavy Copper Broadsword
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 3487;

-- 14727 War Paint Legguards
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 6
WHERE entry = 14727;

-- 26011 Cryo-Core Attendant's Boots
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 26011;

-- 26025 Technician's Boots
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 26025;

-- 30505 Ghostclaw Tunic
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 30505;

-- 1300 Lesser Staff of the Spire
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 1300;

-- 1303 Bridgeworker's Gloves
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 1303;

-- 1314 Ghoul Fingers
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 1314;

-- 1448 Blackrock Gauntlets
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 1448;

-- 2992 Burnished Gloves
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 2992;

-- 4437 Channeler's Staff
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4437;

-- 4788 Agile Boots
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 4788;

-- 5318 Zhovur Axe
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 5318;

-- 5629 Hammerfist Gloves
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 5629;

-- 6731 Ironforge Breastplate
UPDATE item_template
SET
  stat_value2 = 3,
  armor = 198
WHERE entry = 6731;

-- 14729 War Paint Shield
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 2
WHERE entry = 14729;

-- 26013 Cincture of Woven Reeds
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 26013;

-- 26035 Corin's Handguards
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 26035;

-- 1406 Pearl-encrusted Spear
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 1406;

-- 3559 Night Watch Gauntlets
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 3559;

-- 4436 Jewel-encrusted Sash
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 4436;

-- 5958 Fine Leather Pants
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 5958;

-- 22995 Sin'dorei Warblade
UPDATE item_template
SET
  stat_value2 = 10
WHERE entry = 22995;

-- 6333 Spikelash Dagger
UPDATE item_template
SET
  dmg_min1 = 14,
  dmg_max1 = 28
WHERE entry = 6333;

-- 7606 Polar Gauntlets
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 7606;

-- 14569 Bristlebark Bindings
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 14569;

-- 2175 Shadowhide Battle Axe
UPDATE item_template
SET
  dmg_min1 = 39,
  dmg_max1 = 59
WHERE entry = 2175;

-- 3022 Bluegill Breeches
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 3022;

-- 4445 Flesh Carver
UPDATE item_template
SET
  dmg_min1 = 18,
  dmg_max1 = 35
WHERE entry = 4445;

-- 4800 Mighty Chain Pants
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 4800;

-- 4821 Bear Buckler
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 4821;

-- 5540 Pearl-handled Dagger
UPDATE item_template
SET
  dmg_min1 = 13,
  dmg_max1 = 26
WHERE entry = 5540;

-- 5749 Scythe Axe
UPDATE item_template
SET
  dmg_min1 = 43,
  dmg_max1 = 66
WHERE entry = 5749;

-- 5750 Warchief's Girdle
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 5750;

-- 5961 Dark Leather Pants
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 5961;

-- 6481 Dagmire Gauntlets
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 6481;

-- 20425 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 20425;

-- 20426 Advisor's Ring
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 20426;

-- 20431 Lorekeeper's Ring
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 20431;

-- 20434 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 20434;

-- 885 Black Metal Axe
UPDATE item_template
SET
  dmg_min1 = 18,
  dmg_max1 = 34
WHERE entry = 885;

-- 1449 Minor Channeling Ring
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 4
WHERE entry = 1449;

-- 1459 Shadowhide Scalper
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 1459;

-- 1935 Assassin's Blade
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 1935;

-- 2035 Sword of the Night Sky
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 2
WHERE entry = 2035;

-- 3741 Stomping Boots
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 3741;

-- 4706 Lambent Scale Cloak
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 4706;

-- 4793 Sylvan Cloak
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 4793;

-- 4818 Executioner's Sword
UPDATE item_template
SET
  dmg_min1 = 43,
  dmg_max1 = 65
WHERE entry = 4818;

-- 10048 Colorful Kilt
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 5
WHERE entry = 10048;

-- 16890 Slatemetal Cutlass
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 2
WHERE entry = 16890;

-- 911 Ironwood Treebranch
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 911;

-- 1292 Butcher's Cleaver
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1292;

-- 2910 Gold Militia Boots
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5
WHERE entry = 2910;

-- 3413 Doomspike
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 3413;

-- 3490 Deadly Bronze Poniard
UPDATE item_template
SET
  dmg_min1 = 16,
  dmg_max1 = 30
WHERE entry = 3490;

-- 3491 Heavy Bronze Mace
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 3491;

-- 5313 Totemic Clan Ring
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 5313;

-- 6630 Seedcloud Buckler
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 6630;

-- 6669 Sacred Band
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 4
WHERE entry = 6669;

-- 14375 Sanguine Cuffs
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 2
WHERE entry = 14375;

-- 15894 Bristlebark Buckler
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 15894;

-- 1077 Defias Mage Ring
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 1077;

-- 3056 Forest Leather Pants
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6
WHERE entry = 3056;

-- 3417 Onyx Claymore
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value3 = 9
WHERE entry = 3417;

-- 4318 Gloves of Meditation
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 4318;

-- 4454 Talon of Vultros
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 4454;

-- 4713 Silver-thread Cloak
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 4713;

-- 1276 Fire Hardened Buckler
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1276;

-- 3047 Lambent Scale Gloves
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 3
WHERE entry = 3047;

-- 3069 Bright Robe
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 3069;

-- 4036 Silver-thread Cuffs
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 4036;

-- 4828 Nightwind Belt
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 4828;

-- 6608 Bright Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 6608;

-- 6668 Draftsman Boots
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 6668;

-- 16660 Driftmire Shield
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 16660;

-- 57305 Axe of Grounded Flame
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 57305;

-- 63346 Wicked Dagger
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 63346;

-- 72981 Zealous Sword
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 72981;

-- 3203 Dense Triangle Mace
UPDATE item_template
SET
  dmg_min1 = 44,
  dmg_max1 = 66
WHERE entry = 3203;

-- 14750 Slayer's Cuffs
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 8
WHERE entry = 14750;

-- 756 Tunnel Pick
UPDATE item_template
SET
  dmg_min1 = 49,
  dmg_max1 = 74
WHERE entry = 756;

-- 897 Madwolf Bracers
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 897;

-- 913 Huge Ogre Sword
UPDATE item_template
SET
  dmg_min1 = 60,
  dmg_max1 = 90
WHERE entry = 913;

-- 2014 Black Metal Greatsword
UPDATE item_template
SET
  dmg_min1 = 52,
  dmg_max1 = 78
WHERE entry = 2014;

-- 3492 Mighty Iron Hammer
UPDATE item_template
SET
  stat_value1 = 5,
  dmg_min1 = 30,
  dmg_max1 = 57
WHERE entry = 3492;

-- 5770 Robes of Arcana
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 7
WHERE entry = 5770;

-- 6198 Jurassic Wristguards
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 6198;

-- 6386 Glimmering Mail Legguards
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 7
WHERE entry = 6386;

-- 9535 Fire-welded Bracers
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 9535;

-- 14406 Resilient Cord
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 4
WHERE entry = 14406;

-- 791 Gnarled Ash Staff
UPDATE item_template
SET
  dmg_min1 = 65,
  dmg_max1 = 99
WHERE entry = 791;

-- 4255 Green Leather Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8
WHERE entry = 4255;

-- 12249 Merciless Axe
UPDATE item_template
SET
  dmg_min1 = 54,
  dmg_max1 = 81
WHERE entry = 12249;

-- 15928 Silver-thread Rod
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 15928;

-- 3849 Hardened Iron Shortsword
UPDATE item_template
SET
  stat_value1 = 5,
  dmg_min1 = 21,
  dmg_max1 = 39
WHERE entry = 3849;

-- 4716 Combat Cloak
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4716;

-- 5820 Faerie Mantle
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6
WHERE entry = 5820;

-- 6194 Barreling Reaper
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 6194;

-- 6689 Wind Spirit Staff
UPDATE item_template
SET
  dmg_min1 = 70,
  dmg_max1 = 106
WHERE entry = 6689;

-- 12247 Broad Bladed Knife
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 12247;

-- 14585 Dokebi Leggings
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 7,
  stat_value3 = 6
WHERE entry = 14585;

-- 14763 Enduring Cape
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 14763;

-- 24118 Signet of Argas
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 24118;

-- 24119 Band of Argas
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 24119;

-- 2953 Watch Master's Cloak
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 2953;

-- 4643 Grimsteel Cape
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4643;

-- 6745 Swiftrunner Cape
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 6745;

-- 9699 Garrison Cloak
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 3
WHERE entry = 9699;

-- 14398 Resilient Tunic
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 11
WHERE entry = 14398;

-- 14405 Resilient Robe
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 11
WHERE entry = 14405;

-- 19545 Scout's Blade
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 19545;

-- 19549 Sentinel's Blade
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 19549;

-- 20114 Highlander's Leather Boots
UPDATE item_template
SET
  armor = 104
WHERE entry = 20114;

-- 20188 Defiler's Leather Boots
UPDATE item_template
SET
  armor = 104
WHERE entry = 20188;

-- 1991 Goblin Power Shovel
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 10
WHERE entry = 1991;

-- 4075 Mail Combat Gauntlets
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 4
WHERE entry = 4075;

-- 14416 Stonecloth Bindings
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 14416;

-- 14759 Enduring Bracers
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 6
WHERE entry = 14759;

-- 151082 Lead Apron
UPDATE item_template
SET
  stat_value1 = 28,
  stat_value2 = 4,
  stat_value3 = 6
WHERE entry = 151082;

-- 3850 Jade Serpentblade
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 3850;

-- 6691 Swinetusk Shank
UPDATE item_template
SET
  dmg_min1 = 24,
  dmg_max1 = 45
WHERE entry = 6691;

-- 7687 Ironspine's Fist
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 7687;

-- 15588 Bracesteel Belt
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 8
WHERE entry = 15588;

-- 1522 Headhunting Spear
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 6
WHERE entry = 1522;

-- 1993 Ogremind Ring
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 3
WHERE entry = 1993;

-- 3853 Moonsteel Broadsword
UPDATE item_template
SET
  dmg_min1 = 55,
  dmg_max1 = 83
WHERE entry = 3853;

-- 6784 Braced Handguards
UPDATE item_template
SET
  stat_value2 = 7
WHERE entry = 6784;

-- 9384 Stonevault Shiv
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 9384;

-- 10358 Duracin Bracers
UPDATE item_template
SET
  stat_value2 = 7
WHERE entry = 10358;

-- 10359 Everlast Boots
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 10359;

-- 14588 Hawkeye's Cord
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 8,
  stat_value3 = 6
WHERE entry = 14588;

-- 33229 Mordant's Travel Tunic
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 7
WHERE entry = 33229;

-- 1996 Voodoo Band
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 3
WHERE entry = 1996;

-- 2622 Nimar's Tribal Headdress
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 7,
  stat_value3 = 10
WHERE entry = 2622;

-- 4038 Nightsky Robe
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8,
  stat_value3 = 8
WHERE entry = 4038;

-- 4115 Grom'gol Buckler
UPDATE item_template
SET
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 4115;

-- 7111 Nightsky Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8,
  stat_value3 = 8
WHERE entry = 7111;

-- 10329 Scarlet Belt
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 7
WHERE entry = 10329;

-- 10573 Boneslasher
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 16,
  stat_value3 = 5
WHERE entry = 10573;

-- 14607 Hawkeye's Buckler
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 6
WHERE entry = 14607;

-- 15455 Dustfall Robes
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 8
WHERE entry = 15455;

-- 6421 Glyphed Belt
UPDATE item_template
SET
  stat_value2 = 6,
  stat_value3 = 5
WHERE entry = 6421;

-- 7761 Steelclaw Reaver
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value2 = 8
WHERE entry = 7761;

-- 9718 Reforged Blade of Heroes
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 3,
  dmg_min1 = 31,
  dmg_max1 = 59
WHERE entry = 9718;

-- 13081 Skullance Shield
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 5,
  stat_value3 = 4
WHERE entry = 13081;

-- 15697 Kodo Rustler Boots
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 5
WHERE entry = 15697;

-- 16791 Silkstream Cuffs
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 4
WHERE entry = 16791;

-- 33264 Glowing Tourmaline Ring
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 33264;

-- 33272 Biting Axe
UPDATE item_template
SET
  dmg_min1 = 23,
  dmg_max1 = 43
WHERE entry = 33272;

-- 7713 Illusionary Rod
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10,
  stat_value3 = 7
WHERE entry = 7713;

-- 15104 Wingborne Boots
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 15104;

-- 33240 Grimtotem Earthbinder's Tunic
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 8
WHERE entry = 33240;

-- 33261 Destroyer's Cloak
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6
WHERE entry = 33261;

-- 1659 Engineering Gloves
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8
WHERE entry = 1659;

-- 4329 Star Belt
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 13
WHERE entry = 4329;

-- 8158 Jouster's Gauntlets
UPDATE item_template
SET
  armor = 166
WHERE entry = 8158;

-- 14422 Silksand Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 14422;

-- 14598 Warden's Waistband
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4,
  stat_value3 = 6
WHERE entry = 14598;

-- 14772 Ravager's Handwraps
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 6
WHERE entry = 14772;

-- 33263 Raptor Eye Ring
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 4
WHERE entry = 33263;

-- 4116 Olmann Sewar
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 4116;

-- 4548 Servomechanic Sledgehammer
UPDATE item_template
SET
  dmg_min1 = 53,
  dmg_max1 = 80
WHERE entry = 4548;

-- 9366 Golden Scale Gauntlets
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 4
WHERE entry = 9366;

-- 9424 Ginn-su Sword
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 9424;

-- 14826 Symbolic Gauntlets
UPDATE item_template
SET
  stat_value1 = 9,
  armor = 188
WHERE entry = 14826;

-- 6774 Uthek's Finger
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 5,
  stat_value3 = 5
WHERE entry = 6774;

-- 7941 Heavy Mithril Axe
UPDATE item_template
SET
  stat_value1 = 7,
  dmg_min1 = 45,
  dmg_max1 = 85
WHERE entry = 7941;

-- 9427 Stonevault Bonebreaker
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 9427;

-- 14421 Silksand Circlet
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 9,
  stat_value3 = 10
WHERE entry = 14421;

-- 14430 Windchaser Cloak
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 4
WHERE entry = 14430;

-- 4063 Imperial Leather Gloves
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 9
WHERE entry = 4063;

-- 9661 Earthclasp Barrier
UPDATE item_template
SET
  armor = 1257
WHERE entry = 9661;

-- 9680 Tok'kar's Murloc Shanker
UPDATE item_template
SET
  dmg_min1 = 28,
  dmg_max1 = 52
WHERE entry = 9680;

-- 14838 Tyrant's Belt
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 3
WHERE entry = 14838;

-- 20098 Highlander's Cloth Girdle
UPDATE item_template
SET
  armor = 105
WHERE entry = 20098;

-- 20101 Highlander's Lizardhide Boots
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 6,
  stat_value3 = 5,
  stat_value4 = 6,
  armor = 129
WHERE entry = 20101;

-- 20104 Highlander's Lizardhide Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20104;

-- 20113 Highlander's Leather Boots
UPDATE item_template
SET
  armor = 129
WHERE entry = 20113;

-- 20116 Highlander's Leather Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20116;

-- 20166 Defiler's Cloth Girdle
UPDATE item_template
SET
  armor = 105
WHERE entry = 20166;

-- 20168 Defiler's Lizardhide Boots
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 6,
  stat_value3 = 5,
  stat_value4 = 6,
  armor = 129
WHERE entry = 20168;

-- 20173 Defiler's Lizardhide Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20173;

-- 20187 Defiler's Leather Boots
UPDATE item_template
SET
  armor = 129
WHERE entry = 20187;

-- 20192 Defiler's Leather Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20192;

-- 7726 Aegis of the Scarlet Commander
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 8,
  stat_value3 = 7
WHERE entry = 7726;

-- 7942 Blue Glittering Axe
UPDATE item_template
SET
  dmg_min1 = 32,
  dmg_max1 = 61
WHERE entry = 7942;

-- 14428 Windchaser Footpads
UPDATE item_template
SET
  stat_value3 = 12
WHERE entry = 14428;

-- 14654 Scorpashi Wristbands
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 6
WHERE entry = 14654;

-- 4080 Blackforge Cowl
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7,
  stat_value3 = 7
WHERE entry = 4080;

-- 4652 Salbac Shield
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 3
WHERE entry = 4652;

-- 7943 Wicked Mithril Blade
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 4
WHERE entry = 7943;

-- 9411 Rockshard Pauldrons
UPDATE item_template
SET
  stat_value2 = 9,
  stat_value3 = 9
WHERE entry = 9411;

-- 10018 Red Mageweave Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 11
WHERE entry = 10018;

-- 10021 Dreamweave Vest
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 9,
  stat_value3 = 18
WHERE entry = 10021;

-- 10703 Fiendish Skiv
UPDATE item_template
SET
  dmg_min1 = 35,
  dmg_max1 = 66
WHERE entry = 10703;

-- 11856 Ceremonial Elven Blade
UPDATE item_template
SET
  dmg_min1 = 33,
  dmg_max1 = 63
WHERE entry = 11856;

-- 14604 Warden's Wizard Hat
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 11,
  stat_value3 = 3
WHERE entry = 14604;

-- 18341 Quel'dorei Sash
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 13
WHERE entry = 18341;

-- 18342 Quel'dorei Guard
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 7,
  stat_value3 = 7
WHERE entry = 18342;

-- 8135 Chromite Shield
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value2 = 10
WHERE entry = 8135;

-- 8195 Nightscape Cloak
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 8195;

-- 12255 Pale Leggings
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12
WHERE entry = 12255;

-- 8110 Hibernal Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10
WHERE entry = 8110;

-- 8121 Heraldic Gloves
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10
WHERE entry = 8121;

-- 8115 Hibernal Cowl
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 14
WHERE entry = 8115;

-- 8216 Big Voodoo Cloak
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 5
WHERE entry = 8216;

-- 9480 Eyegouger
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 10
WHERE entry = 9480;

-- 13018 Executioner's Cleaver
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 10
WHERE entry = 13018;

-- 16738 Witherseed Gloves
UPDATE item_template
SET
  stat_value1 = 13
WHERE entry = 16738;

-- 19039 Zorbin's Water Resistant Hat
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 9,
  stat_value3 = 8
WHERE entry = 19039;

-- 19040 Zorbin's Mega-Slicer
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5
WHERE entry = 19040;

-- 19041 Pratt's Handcrafted Tunic
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 15,
  stat_value3 = 12
WHERE entry = 19041;

-- 19042 Jangdor's Handcrafted Tunic
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 15,
  stat_value3 = 12
WHERE entry = 19042;

-- 19123 Everwarm Handwraps
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 19123;

-- 7946 Runed Mithril Hammer
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 4
WHERE entry = 7946;

-- 14655 Scorpashi Breastplate
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 8,
  stat_value3 = 4
WHERE entry = 14655;

-- 14658 Scorpashi Skullcap
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 13,
  stat_value3 = 6
WHERE entry = 14658;

-- 14779 Khan's Chestpiece
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 10
WHERE entry = 14779;

-- 8131 Myrmidon's Helm
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 11,
  stat_value3 = 14
WHERE entry = 8131;

-- 14441 Venomshroud Mask
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 10
WHERE entry = 14441;

-- 14846 Sunscale Gauntlets
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7,
  stat_value3 = 6
WHERE entry = 14846;

-- 17755 Satyrmane Sash
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10,
  armor = 40
WHERE entry = 17755;

-- 8282 Valorous Shield
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 9
WHERE entry = 8282;

-- 9685 Will of the Mountain Giant
UPDATE item_template
SET
  dmg_min1 = 88,
  dmg_max1 = 133
WHERE entry = 9685;

-- 10652 Will of the Mountain Giant
UPDATE item_template
SET
  dmg_min1 = 88,
  dmg_max1 = 133
WHERE entry = 10652;

-- 10742 Dragonflight Leggings
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 6,
  stat_value3 = 14
WHERE entry = 10742;

-- 13085 Horizon Choker
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 13085;

-- 14662 Keeper's Hooves
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 12,
  stat_value3 = 6
WHERE entry = 14662;

-- 12055 Stardust Band
UPDATE item_template
SET
  stat_value2 = 5,
  stat_value3 = 3
WHERE entry = 12055;

-- 22230 Frightmaw Hide
UPDATE item_template
SET
  stat_value1 = 15
WHERE entry = 22230;

-- 29970 Wildfeather Leggings
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 12,
  stat_value3 = 16,
  stat_value4 = 28
WHERE entry = 29970;

-- 29971 Dragonstrike Leggings
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 11,
  stat_value3 = 18,
  stat_value4 = 24,
  stat_value5 = 5
WHERE entry = 29971;

-- 8254 Imperial Red Circlet
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 15
WHERE entry = 8254;

-- 11749 Searingscale Leggings
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 13,
  stat_value3 = 13,
  stat_value4 = 13
WHERE entry = 11749;

-- 14849 Sunscale Helmet
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 12,
  stat_value3 = 12
WHERE entry = 14849;

-- 19567 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 11,
  stat_value3 = 9
WHERE entry = 19567;

-- 19571 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 11,
  stat_value3 = 9
WHERE entry = 19571;

-- 20097 Highlander's Cloth Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20097;

-- 20100 Highlander's Lizardhide Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 20100;

-- 20112 Highlander's Leather Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 20112;

-- 20115 Highlander's Leather Girdle
UPDATE item_template
SET
  armor = 136
WHERE entry = 20115;

-- 20165 Defiler's Cloth Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20165;

-- 20170 Defiler's Lizardhide Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 20170;

-- 20189 Defiler's Leather Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 20189;

-- 20193 Defiler's Leather Girdle
UPDATE item_template
SET
  armor = 136
WHERE entry = 20193;

-- 10842 Windscale Sarong
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 7
WHERE entry = 10842;

-- 11662 Ban'thok Sash
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 11,
  stat_value3 = 8,
  stat_value4 = 12
WHERE entry = 11662;

-- 14437 Venomshroud Vest
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 18
WHERE entry = 14437;

-- 14790 Protector Buckler
UPDATE item_template
SET
  stat_value2 = 5,
  stat_value3 = 10
WHERE entry = 14790;

-- 17710 Charstone Dirk
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 3
WHERE entry = 17710;

-- 17714 Bracers of the Stone Princess
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5,
  stat_value3 = 30
WHERE entry = 17714;

-- 9649 Royal Highmark Vestments
UPDATE item_template
SET
  stat_value2 = 3,
  stat_value3 = 16
WHERE entry = 9649;

-- 10782 Hakkari Shroud
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 15
WHERE entry = 10782;

-- 13120 Deepfury Bracers
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 4,
  stat_value3 = 8
WHERE entry = 13120;

-- 13122 Dark Phantom Cape
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 6
WHERE entry = 13122;

-- 15702 Chemist's Ring
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 4
WHERE entry = 15702;

-- 19596 Dryad's Wrist Bindings
UPDATE item_template
SET
  armor = 37
WHERE entry = 19596;

-- 11874 Clouddrift Mantle
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 12
WHERE entry = 11874;

-- 15789 Deep River Cloak
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 11
WHERE entry = 15789;

-- 18296 Marksman Bands
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 6,
  stat_value3 = 10
WHERE entry = 18296;

-- 11731 Savage Gladiator Greaves
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 20,
  stat_value3 = 13
WHERE entry = 11731;

-- 13182 Phase Blade
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7
WHERE entry = 13182;

-- 14813 Warstrike Cape
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 10
WHERE entry = 14813;

-- 16697 Devout Bracers
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 7
WHERE entry = 16697;

-- 22205 Black Steel Bindings
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 14
WHERE entry = 22205;

-- 22256 Mana Shaping Handwraps
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 9,
  stat_value3 = 7,
  stat_value4 = 16
WHERE entry = 22256;

-- 12059 Conqueror's Medallion
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 10,
  stat_value3 = 5,
  stat_value4 = 4
WHERE entry = 12059;

-- 16680 Beaststalker's Belt
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 18,
  stat_value5 = 6
WHERE entry = 16680;

-- 18302 Band of Vigor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 7,
  stat_value3 = 7
WHERE entry = 18302;

-- 18303 Nimble Buckler
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 12
WHERE entry = 18303;

-- 18324 Waveslicer
UPDATE item_template
SET
  stat_value1 = 26,
  stat_value2 = 14
WHERE entry = 18324;

-- 12554 Hands of the Exalted Herald
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12,
  stat_value3 = 18
WHERE entry = 12554;

-- 12557 Ebonsteel Spaulders
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 14,
  stat_value3 = 6,
  armor = 553
WHERE entry = 12557;

-- 12626 Funeral Cuffs
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 5
WHERE entry = 12626;

-- 13101 Wolfrunner Shoes
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 11,
  stat_value3 = 11,
  stat_value4 = 13
WHERE entry = 13101;

-- 13395 Skul's Fingerbone Claws
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 40
WHERE entry = 13395;

-- 14453 Highborne Robes
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15
WHERE entry = 14453;

-- 14455 Highborne Padded Armor
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15
WHERE entry = 14455;

-- 14800 Bloodlust Buckler
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 11
WHERE entry = 14800;

-- 16712 Shadowcraft Gloves
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 18
WHERE entry = 16712;

-- 18023 Blood Ruby Pendant
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10
WHERE entry = 18023;

-- 8308 Hero's Band
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 14,
  stat_value3 = 17
WHERE entry = 8308;

-- 13252 Cloudrunner Girdle
UPDATE item_template
SET
  armor = 185
WHERE entry = 13252;

-- 13373 Band of Flesh
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 6,
  stat_value3 = 3
WHERE entry = 13373;

-- 13374 Soulstealer Mantle
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 22
WHERE entry = 13374;

-- 13959 Omokk's Girth Restrainer
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 9,
  stat_value3 = 14
WHERE entry = 13959;

-- 16370 Knight-Captain's Silk Cuffs
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 16370;

-- 16407 Knight-Captain's Plate Girdle
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 8,
  stat_value3 = 12,
  stat_value4 = 6
WHERE entry = 16407;

-- 16511 Legionnaire's Plate Cinch
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 8,
  stat_value3 = 12,
  stat_value4 = 6
WHERE entry = 16511;

-- 17563 Knight-Captain's Dreadweave Bracers
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 17563;

-- 17575 Legionnaire's Dreadweave Bracers
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 17575;

-- 17595 Knight-Captain's Satin Cuffs
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 17595;

-- 17615 Legionnaire's Satin Cuffs
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 17615;

-- 18048 Mastersmith's Hammer
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 18048;

-- 18369 Gordok's Handwraps
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 14
WHERE entry = 18369;

-- 18494 Denwatcher's Shoulders
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 18
WHERE entry = 18494;

-- 19575 Strength of Mugamba
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 7,
  stat_value3 = 10,
  stat_value4 = 6
WHERE entry = 19575;

-- 19603 Kezan's Taint
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 6,
  stat_value3 = 12
WHERE entry = 19603;

-- 20693 Weighted Cloak
UPDATE item_template
SET
  armor = 99
WHERE entry = 20693;

-- 22069 Sorcerer's Robes
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 9,
  stat_value3 = 14,
  stat_value4 = 16
WHERE entry = 22069;

-- 22075 Deathmist Robe
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 27,
  stat_value3 = 14,
  stat_value4 = 12
WHERE entry = 22075;

-- 22083 Virtuous Robe
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 12,
  stat_value3 = 21,
  stat_value4 = 14,
  stat_value5 = 8
WHERE entry = 22083;

-- 22204 Wristguards of Renown
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 10,
  stat_value3 = 10
WHERE entry = 22204;

-- 22207 Sash of the Grand Hunt
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 14,
  stat_value3 = 6,
  stat_value4 = 8
WHERE entry = 22207;

-- 23124 Staff of Balzaphon
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 10,
  stat_value3 = 7,
  stat_value4 = 14
WHERE entry = 23124;

-- 34658 Plague Band
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 6,
  stat_value3 = 4
WHERE entry = 34658;

-- 14612 Bloodmail Legguards
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 16,
  stat_value3 = 30,
  stat_value4 = 12
WHERE entry = 14612;

-- 14614 Bloodmail Belt
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 9,
  stat_value3 = 12,
  stat_value4 = 24
WHERE entry = 14614;

-- 14638 Cadaverous Leggings
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 52
WHERE entry = 14638;

-- 16719 Wildheart Kilt
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 14,
  stat_value3 = 14,
  stat_value4 = 26,
  stat_value5 = 12
WHERE entry = 16719;

-- 18347 Well Balanced Axe
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 18347;

-- 18386 Padre's Trousers
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 22,
  stat_value3 = 8
WHERE entry = 18386;

-- 18680 Ancient Bone Bow
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 18680;

-- 18740 Thuzadin Sash
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 11,
  stat_value3 = 11,
  stat_value4 = 11
WHERE entry = 18740;

-- 22232 Marksman's Girdle
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 10
WHERE entry = 22232;

-- 22304 Ironweave Gloves
UPDATE item_template
SET
  armor = 144
WHERE entry = 22304;

-- 22472 Boots of Ferocity
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 13,
  stat_value3 = 26
WHERE entry = 22472;

-- 13083 Garrett Family Crest
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 4,
  stat_value3 = 17
WHERE entry = 13083;

-- 13936 Dreadmaster's Shroud
UPDATE item_template
SET
  armor = 120
WHERE entry = 13936;

-- 13950 Detention Strap
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 11,
  stat_value3 = 10
WHERE entry = 13950;

-- 13951 Vigorsteel Vambraces
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 14
WHERE entry = 13951;

-- 16996 Gorewood Bow
UPDATE item_template
SET
  stat_value1 = 9
WHERE entry = 16996;

-- 16998 Sacred Protector
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10
WHERE entry = 16998;

-- 18389 Cloak of the Cosmos
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 7,
  stat_value3 = 14
WHERE entry = 18389;

-- 18395 Emerald Flame Ring
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 8,
  stat_value3 = 7,
  stat_value4 = 8
WHERE entry = 18395;

-- 18507 Boots of the Full Moon
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 9,
  stat_value3 = 12,
  stat_value4 = 14
WHERE entry = 18507;

-- 18689 Phantasmal Cloak
UPDATE item_template
SET
  armor = 114
WHERE entry = 18689;

-- 18693 Shivery Handwraps
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 9
WHERE entry = 18693;

-- 18695 Spellbound Tome
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 6,
  stat_value3 = 3
WHERE entry = 18695;

-- 18754 Fel Hardened Bracers
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 5
WHERE entry = 18754;

-- 21179 Band of Earthen Wrath
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 14,
  stat_value3 = 4
WHERE entry = 21179;

-- 22334 Band of Mending
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 7,
  stat_value3 = 6,
  stat_value4 = 16
WHERE entry = 22334;

-- 12587 Eye of Rend
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 26,
  stat_value3 = 28
WHERE entry = 12587;

-- 13023 Eaglehorn Long Bow
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 4
WHERE entry = 13023;

-- 13142 Brigam Girdle
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 16
WHERE entry = 13142;

-- 13345 Seal of Rivendare
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 7
WHERE entry = 13345;

-- 13502 Handcrafted Mastersmith Girdle
UPDATE item_template
SET
  armor = 519
WHERE entry = 13502;

-- 15411 Mark of Fordring
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 26
WHERE entry = 15411;

-- 16405 Knight-Lieutenant's Plate Boots
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 8,
  stat_value3 = 10
WHERE entry = 16405;

-- 16409 Knight-Lieutenant's Lamellar Sabatons
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 15,
  stat_value3 = 7,
  stat_value4 = 12
WHERE entry = 16409;

-- 16421 Knight-Captain's Dragonhide Tunic
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 26,
  stat_value3 = 9,
  stat_value4 = 8,
  stat_value5 = 14,
  stat_value6 = 16
WHERE entry = 16421;

-- 16504 Legionnaire's Dragonhide Breastplate
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 26,
  stat_value3 = 9,
  stat_value4 = 8,
  stat_value5 = 14,
  stat_value6 = 16
WHERE entry = 16504;

-- 16509 Blood Guard's Plate Boots
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 8,
  stat_value3 = 10
WHERE entry = 16509;

-- 18538 Treant's Bane
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 15,
  stat_value3 = 28
WHERE entry = 18538;

-- 18872 Manastorm Leggings
UPDATE item_template
SET
  armor = 85
WHERE entry = 18872;

-- 19106 Ice Barbed Spear
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 13,
  stat_value3 = 20
WHERE entry = 19106;

-- 19110 Cold Forged Blade
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 5
WHERE entry = 19110;

-- 19566 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 13,
  stat_value3 = 10
WHERE entry = 19566;

-- 19570 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 13,
  stat_value3 = 10
WHERE entry = 19570;

-- 20041 Highlander's Plate Girdle
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 10,
  stat_value3 = 14
WHERE entry = 20041;

-- 20045 Highlander's Leather Girdle
UPDATE item_template
SET
  armor = 159
WHERE entry = 20045;

-- 20047 Highlander's Cloth Girdle
UPDATE item_template
SET
  armor = 150
WHERE entry = 20047;

-- 20049 Highlander's Lamellar Greaves
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 8,
  stat_value3 = 24,
  stat_value4 = 8
WHERE entry = 20049;

-- 20052 Highlander's Leather Boots
UPDATE item_template
SET
  armor = 181
WHERE entry = 20052;

-- 20053 Highlander's Lizardhide Boots
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 8,
  stat_value3 = 8,
  stat_value4 = 16,
  armor = 181
WHERE entry = 20053;

-- 20163 Defiler's Cloth Girdle
UPDATE item_template
SET
  armor = 150
WHERE entry = 20163;

-- 20167 Defiler's Lizardhide Boots
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 8,
  stat_value3 = 8,
  stat_value4 = 16,
  armor = 181
WHERE entry = 20167;

-- 20181 Defiler's Lamellar Greaves
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 8,
  stat_value3 = 24,
  stat_value4 = 8
WHERE entry = 20181;

-- 20186 Defiler's Leather Boots
UPDATE item_template
SET
  armor = 181
WHERE entry = 20186;

-- 20190 Defiler's Leather Girdle
UPDATE item_template
SET
  armor = 159
WHERE entry = 20190;

-- 20204 Defiler's Plate Girdle
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 10,
  stat_value3 = 14
WHERE entry = 20204;

-- 20712 Wastewalker's Gauntlets
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 10,
  stat_value5 = 10
WHERE entry = 20712;

-- 20715 Dunestalker's Boots
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 10,
  stat_value3 = 18
WHERE entry = 20715;

-- 22150 Beads of Ogre Might
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 10,
  stat_value3 = 24
WHERE entry = 22150;

-- 22247 Faith Healer's Boots
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 10,
  stat_value4 = 14
WHERE entry = 22247;

-- 22326 Amalgam's Band
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5,
  stat_value3 = 14,
  stat_value4 = 4
WHERE entry = 22326;

-- 22410 Gauntlets of Deftness
UPDATE item_template
SET
  armor = 311
WHERE entry = 22410;

-- 14456 Elunarian Vest
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 21,
  stat_value3 = 5
WHERE entry = 14456;

-- 14464 Elunarian Silk Robes
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 21,
  stat_value3 = 5
WHERE entry = 14464;

-- 14812 Warstrike Buckler
UPDATE item_template
SET
  stat_value2 = 15
WHERE entry = 14812;

-- 19050 Mantle of the Timbermaw
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 8
WHERE entry = 19050;

-- 17109 Choker of Enlightenment
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 18
WHERE entry = 17109;

-- 19834 Zandalar Madcap's Tunic
UPDATE item_template
SET
  armor = 197
WHERE entry = 19834;

-- 20061 Highlander's Epaulets
UPDATE item_template
SET
  armor = 196
WHERE entry = 20061;

-- 20176 Defiler's Epaulets
UPDATE item_template
SET
  armor = 196
WHERE entry = 20176;

-- 20259 Shadow Panther Hide Gloves
UPDATE item_template
SET
  armor = 173
WHERE entry = 20259;

-- 21396 Ring of Eternal Justice
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 11,
  stat_value4 = 13
WHERE entry = 21396;

-- 21402 Signet of the Unseen Path
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 11,
  stat_value3 = 8,
  stat_value4 = 24
WHERE entry = 21402;

-- 21994 Belt of Heroism
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 12,
  stat_value3 = 18,
  stat_value4 = 10
WHERE entry = 21994;

-- 22002 Darkmantle Belt
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 13,
  stat_value3 = 20
WHERE entry = 22002;

-- 22004 Darkmantle Bracers
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 7,
  stat_value3 = 14
WHERE entry = 22004;

-- 22011 Beastmaster's Bindings
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 7,
  stat_value3 = 5
WHERE entry = 22011;

-- 22062 Sorcerer's Belt
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 7,
  stat_value3 = 12,
  stat_value4 = 14
WHERE entry = 22062;

-- 22082 Virtuous Mantle
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12,
  stat_value3 = 12,
  stat_value4 = 12
WHERE entry = 22082;

-- 22112 Feralheart Spaulders
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 9,
  stat_value3 = 8,
  stat_value4 = 16,
  stat_value5 = 5,
  stat_value6 = 6,
  stat_value7 = 3
WHERE entry = 22112;

-- 22379 Shivsprocket's Shiv
UPDATE item_template
SET
  stat_value1 = 13
WHERE entry = 22379;

-- 22747 Outrider's Silk Leggings
UPDATE item_template
SET
  armor = 188
WHERE entry = 22747;

-- 22752 Sentinel's Silk Leggings
UPDATE item_template
SET
  armor = 188
WHERE entry = 22752;

-- 16796 Arcanist Leggings
UPDATE item_template
SET
  armor = 101
WHERE entry = 16796;

-- 16802 Arcanist Belt
UPDATE item_template
SET
  armor = 65
WHERE entry = 16802;

-- 16804 Felheart Bracers
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 8,
  stat_value3 = 18,
  stat_value4 = 13,
  armor = 51
WHERE entry = 16804;

-- 16806 Felheart Belt
UPDATE item_template
SET
  armor = 65
WHERE entry = 16806;

-- 16810 Felheart Pants
UPDATE item_template
SET
  armor = 101
WHERE entry = 16810;

-- 16814 Pants of Prophecy
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 20,
  stat_value3 = 18,
  stat_value4 = 12,
  stat_value5 = 8,
  armor = 101
WHERE entry = 16814;

-- 16817 Girdle of Prophecy
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 9,
  stat_value5 = 5,
  armor = 65
WHERE entry = 16817;

-- 16823 Nightslayer Shoulder Pads
UPDATE item_template
SET
  armor = 171
WHERE entry = 16823;

-- 16825 Nightslayer Bracelets
UPDATE item_template
SET
  armor = 100
WHERE entry = 16825;

-- 19135 Blacklight Bracer
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 8,
  stat_value3 = 11,
  stat_value4 = 14
WHERE entry = 19135;

-- 19885 Jin'do's Evil Eye
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 6,
  stat_value3 = 5,
  stat_value4 = 23
WHERE entry = 19885;

-- 19890 Jin'do's Hexxer
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 6,
  stat_value3 = 14
WHERE entry = 19890;

-- 21183 Earthpower Vest
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 14,
  stat_value3 = 25
WHERE entry = 21183;

-- 22007 Darkmantle Pants
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 15,
  stat_value3 = 30
WHERE entry = 22007;

-- 22085 Virtuous Skirt
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 14,
  stat_value3 = 12,
  stat_value4 = 16,
  stat_value5 = 8
WHERE entry = 22085;

-- 22690 Leggings of the Plague Hunter
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10,
  stat_value3 = 16,
  stat_value4 = 14
WHERE entry = 22690;

-- 22843 Blood Guard's Chain Greaves
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 14,
  stat_value3 = 26
WHERE entry = 22843;

-- 22856 Blood Guard's Leather Walkers
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 28,
  armor = 166
WHERE entry = 22856;

-- 22860 Blood Guard's Silk Walkers
UPDATE item_template
SET
  armor = 104
WHERE entry = 22860;

-- 22865 Blood Guard's Dreadweave Handwraps
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 4,
  stat_value3 = 21
WHERE entry = 22865;

-- 22869 Blood Guard's Satin Handwraps
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 5,
  stat_value3 = 21,
  armor = 98
WHERE entry = 22869;

-- 23278 Knight-Lieutenant's Chain Greaves
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 14,
  stat_value3 = 26
WHERE entry = 23278;

-- 23282 Knight-Lieutenant's Dreadweave Handwraps
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 4,
  stat_value3 = 21
WHERE entry = 23282;

-- 23285 Knight-Lieutenant's Leather Walkers
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 28,
  armor = 166
WHERE entry = 23285;

-- 23288 Knight-Lieutenant's Satin Handwraps
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 5,
  stat_value3 = 21,
  armor = 98
WHERE entry = 23288;

-- 23291 Knight-Lieutenant's Silk Walkers
UPDATE item_template
SET
  armor = 104
WHERE entry = 23291;

-- 21403 Cloak of the Unseen Path
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 13,
  stat_value3 = 10,
  stat_value4 = 22
WHERE entry = 21403;

-- 19593 The Eye of Zuldazar
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 13,
  stat_value3 = 8,
  stat_value4 = 9
WHERE entry = 19593;

-- 19600 Pebble of Kajaro
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 8,
  stat_value3 = 8,
  stat_value4 = 9
WHERE entry = 19600;

-- 19841 Zandalar Confessor's Mantle
UPDATE item_template
SET
  armor = 78
WHERE entry = 19841;

-- 19856 The Eye of Hakkar
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 40
WHERE entry = 19856;

-- 19906 Blooddrenched Footpads
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 10,
  stat_value3 = 10
WHERE entry = 19906;

-- 19915 Zulian Defender
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 9,
  stat_value3 = 8
WHERE entry = 19915;

-- 19925 Band of Jin
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 8,
  stat_value3 = 10
WHERE entry = 19925;

-- 19928 Animist's Spaulders
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 12,
  stat_value3 = 11,
  stat_value4 = 20,
  armor = 201
WHERE entry = 19928;

-- 19966 Thrice Strung Longbow DEPRECATED
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 4
WHERE entry = 19966;

-- 19993 Hoodoo Hunting Bow
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 4
WHERE entry = 19993;

-- 22720 Zulian Headdress
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 14,
  stat_value3 = 13,
  stat_value4 = 29
WHERE entry = 22720;

-- 22879 Legionnaire's Leather Chestpiece
UPDATE item_template
SET
  armor = 248
WHERE entry = 22879;

-- 22882 Legionnaire's Satin Legguards
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15,
  stat_value3 = 21,
  stat_value4 = 8,
  armor = 144
WHERE entry = 22882;

-- 22884 Legionnaire's Dreadweave Tunic
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 20,
  stat_value3 = 25
WHERE entry = 22884;

-- 23297 Knight-Captain's Dreadweave Tunic
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 20,
  stat_value3 = 25
WHERE entry = 23297;

-- 23298 Knight-Captain's Leather Chestpiece
UPDATE item_template
SET
  armor = 248
WHERE entry = 23298;

-- 23302 Knight-Captain's Satin Legguards
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15,
  stat_value3 = 21,
  stat_value4 = 8,
  armor = 144
WHERE entry = 23302;

-- 18823 Aged Core Leather Gloves
UPDATE item_template
SET
  armor = 130
WHERE entry = 18823;

-- 21466 Stinger of Ayamiss
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 9,
  stat_value3 = 14
WHERE entry = 21466;

-- 21472 Dustwind Turban
UPDATE item_template
SET
  armor = 86
WHERE entry = 21472;

-- 21506 Pendant of the Shifting Sands
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 14,
  stat_value3 = 6
WHERE entry = 21506;

-- 21507 Amulet of the Shifting Sands
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 8
WHERE entry = 21507;

-- 38663 Blood-soaked Saronite Plated Spaulders
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 15,
  stat_value3 = 10
WHERE entry = 38663;

-- 38668 The Plaguebringer's Girdle
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 18,
  stat_value3 = 9
WHERE entry = 38668;

-- 38671 Valanar's Signet Ring
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 18,
  stat_value3 = 12
WHERE entry = 38671;

-- 16437 Marshal's Silk Footwraps
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 23,
  stat_value3 = 6,
  stat_value4 = 8,
  stat_value5 = 21,
  armor = 125
WHERE entry = 16437;

-- 16440 Marshal's Silk Gloves
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 12,
  stat_value3 = 5,
  stat_value4 = 27,
  armor = 118
WHERE entry = 16440;

-- 16448 Marshal's Dragonhide Gauntlets
UPDATE item_template
SET
  stat_value1 = 40,
  stat_value2 = 19,
  stat_value3 = 15,
  stat_value4 = 12,
  armor = 192
WHERE entry = 16448;

-- 16454 Marshal's Leather Handgrips
UPDATE item_template
SET
  armor = 212
WHERE entry = 16454;

-- 16539 General's Silk Boots
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 14,
  stat_value3 = 6,
  stat_value4 = 8,
  stat_value5 = 21,
  armor = 125
WHERE entry = 16539;

-- 16540 General's Silk Handguards
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 12,
  stat_value3 = 5,
  stat_value4 = 27,
  armor = 118
WHERE entry = 16540;

-- 16555 General's Dragonhide Gloves
UPDATE item_template
SET
  stat_value1 = 40,
  stat_value2 = 19,
  stat_value3 = 15,
  stat_value4 = 12,
  armor = 192
WHERE entry = 16555;

-- 16560 General's Leather Mitts
UPDATE item_template
SET
  armor = 212
WHERE entry = 16560;

-- 17579 Marshal's Dreadweave Leggings
UPDATE item_template
SET
  armor = 149
WHERE entry = 17579;

-- 17583 Marshal's Dreadweave Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 17583;

-- 17586 General's Dreadweave Boots
UPDATE item_template
SET
  armor = 145
WHERE entry = 17586;

-- 17593 General's Dreadweave Pants
UPDATE item_template
SET
  armor = 149
WHERE entry = 17593;

-- 17603 Marshal's Satin Pants
UPDATE item_template
SET
  armor = 179
WHERE entry = 17603;

-- 17607 Marshal's Satin Sandals
UPDATE item_template
SET
  armor = 135
WHERE entry = 17607;

-- 17608 Marshal's Satin Gloves
UPDATE item_template
SET
  armor = 128
WHERE entry = 17608;

-- 17618 General's Satin Boots
UPDATE item_template
SET
  armor = 135
WHERE entry = 17618;

-- 17620 General's Satin Gloves
UPDATE item_template
SET
  armor = 128
WHERE entry = 17620;

-- 17625 General's Satin Leggings
UPDATE item_template
SET
  armor = 179
WHERE entry = 17625;

-- 19869 Blooddrenched Grips
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 14,
  stat_value3 = 34
WHERE entry = 19869;

-- 19886 The Hexxer's Cover
UPDATE item_template
SET
  armor = 81
WHERE entry = 19886;

-- 19895 Bloodtinged Kilt
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 20,
  stat_value3 = 28
WHERE entry = 19895;

-- 20627 Dark Heart Pants
UPDATE item_template
SET
  armor = 296
WHERE entry = 20627;

-- 20631 Mendicant's Slippers
UPDATE item_template
SET
  armor = 75
WHERE entry = 20631;

-- 20632 Mindtear Band
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6,
  stat_value3 = 14,
  stat_value4 = 22
WHERE entry = 20632;

-- 21501 Toughened Silithid Hide Gloves
UPDATE item_template
SET
  armor = 182
WHERE entry = 21501;

-- 21503 Belt of the Sand Reaver
UPDATE item_template
SET
  armor = 494
WHERE entry = 21503;

-- 20618 Gloves of Delusional Power
UPDATE item_template
SET
  armor = 69
WHERE entry = 20618;

-- 20623 Circlet of Restless Dreams
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 38,
  stat_value3 = 14,
  armor = 175
WHERE entry = 20623;

-- 21461 Leggings of the Black Blizzard
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 8,
  stat_value3 = 14,
  stat_value4 = 14,
  stat_value5 = 41,
  armor = 97
WHERE entry = 21461;

-- 21462 Gloves of Dark Wisdom
UPDATE item_template
SET
  armor = 69
WHERE entry = 21462;

-- 19370 Mantle of the Blackwing Cabal
UPDATE item_template
SET
  armor = 84
WHERE entry = 19370;

-- 16441 Field Marshal's Coronet
UPDATE item_template
SET
  armor = 175
WHERE entry = 16441;

-- 16443 Field Marshal's Silk Vestments
UPDATE item_template
SET
  stat_value1 = 28,
  stat_value2 = 17,
  stat_value3 = 6,
  stat_value4 = 14,
  stat_value5 = 33,
  armor = 199
WHERE entry = 16443;

-- 16444 Field Marshal's Silk Spaulders
UPDATE item_template
SET
  armor = 147
WHERE entry = 16444;

-- 16455 Field Marshal's Leather Mask
UPDATE item_template
SET
  armor = 254
WHERE entry = 16455;

-- 16457 Field Marshal's Leather Epaulets
UPDATE item_template
SET
  armor = 238
WHERE entry = 16457;

-- 16533 Warlord's Silk Cowl
UPDATE item_template
SET
  armor = 175
WHERE entry = 16533;

-- 16535 Warlord's Silk Raiment
UPDATE item_template
SET
  stat_value1 = 28,
  stat_value2 = 17,
  stat_value3 = 6,
  stat_value4 = 14,
  stat_value5 = 33,
  armor = 199
WHERE entry = 16535;

-- 16536 Warlord's Silk Amice
UPDATE item_template
SET
  armor = 147
WHERE entry = 16536;

-- 16561 Warlord's Leather Helm
UPDATE item_template
SET
  armor = 254
WHERE entry = 16561;

-- 16562 Warlord's Leather Spaulders
UPDATE item_template
SET
  armor = 238
WHERE entry = 16562;

-- 17578 Field Marshal's Coronal
UPDATE item_template
SET
  armor = 145
WHERE entry = 17578;

-- 17580 Field Marshal's Dreadweave Shoulders
UPDATE item_template
SET
  armor = 127
WHERE entry = 17580;

-- 17581 Field Marshal's Dreadweave Robe
UPDATE item_template
SET
  armor = 169
WHERE entry = 17581;

-- 17590 Warlord's Dreadweave Mantle
UPDATE item_template
SET
  armor = 127
WHERE entry = 17590;

-- 17591 Warlord's Dreadweave Hood
UPDATE item_template
SET
  armor = 145
WHERE entry = 17591;

-- 17592 Warlord's Dreadweave Robe
UPDATE item_template
SET
  armor = 169
WHERE entry = 17592;

-- 17602 Field Marshal's Headdress
UPDATE item_template
SET
  armor = 175
WHERE entry = 17602;

-- 17604 Field Marshal's Satin Mantle
UPDATE item_template
SET
  armor = 157
WHERE entry = 17604;

-- 17622 Warlord's Satin Mantle
UPDATE item_template
SET
  armor = 157
WHERE entry = 17622;

-- 17623 Warlord's Satin Cowl
UPDATE item_template
SET
  armor = 175
WHERE entry = 17623;

-- 19403 Band of Forced Concentration
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 9,
  stat_value3 = 8,
  stat_value4 = 21
WHERE entry = 19403;

-- 21693 Guise of the Devourer
UPDATE item_template
SET
  armor = 250
WHERE entry = 21693;

-- 21694 Ternary Mantle
UPDATE item_template
SET
  armor = 86
WHERE entry = 21694;

-- 16905 Bloodfang Chestpiece
UPDATE item_template
SET
  stat_value1 = 26,
  stat_value2 = 17,
  stat_value3 = 24,
  stat_value4 = 20,
  stat_value5 = 14
WHERE entry = 16905;

-- 16906 Bloodfang Boots
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 17,
  stat_value3 = 12,
  stat_value4 = 12
WHERE entry = 16906;

-- 16914 Netherwind Crown
UPDATE item_template
SET
  armor = 107
WHERE entry = 16914;

-- 16915 Netherwind Pants
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 5,
  stat_value3 = 16,
  stat_value4 = 14,
  stat_value5 = 30
WHERE entry = 16915;

-- 16916 Netherwind Robes
UPDATE item_template
SET
  stat_value1 = 26,
  stat_value2 = 8,
  stat_value3 = 16,
  stat_value4 = 14,
  stat_value5 = 32
WHERE entry = 16916;

-- 16921 Halo of Transcendence
UPDATE item_template
SET
  armor = 107
WHERE entry = 16921;

-- 16922 Leggings of Transcendence
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 21,
  stat_value3 = 16,
  stat_value4 = 25,
  stat_value5 = 9
WHERE entry = 16922;

-- 16923 Robes of Transcendence
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 16,
  stat_value3 = 17,
  stat_value4 = 30
WHERE entry = 16923;

-- 16928 Nemesis Gloves
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 17,
  stat_value3 = 14,
  stat_value4 = 15
WHERE entry = 16928;

-- 16930 Nemesis Leggings
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 4,
  stat_value3 = 23,
  stat_value4 = 39
WHERE entry = 16930;

-- 16931 Nemesis Robes
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 8,
  stat_value3 = 26,
  stat_value4 = 14,
  stat_value5 = 32
WHERE entry = 16931;

-- 16938 Dragonstalker's Legguards
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 15,
  stat_value3 = 8,
  stat_value4 = 16,
  stat_value5 = 10,
  stat_value6 = 14,
  stat_value7 = 40
WHERE entry = 16938;

-- 21645 Hive Tunneler's Boots
UPDATE item_template
SET
  armor = 216
WHERE entry = 21645;

-- 817106 High Priestess Arlokk's Defender
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 9,
  stat_value3 = 22,
  stat_value4 = 10
WHERE entry = 817106;

-- 19138 Band of Sulfuras
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 10,
  stat_value3 = 13
WHERE entry = 19138;

-- 21344 Enigma Boots
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 6,
  stat_value3 = 15,
  stat_value4 = 8,
  stat_value5 = 28,
  stat_value6 = 5
WHERE entry = 21344;

-- 21349 Footwraps of the Oracle
UPDATE item_template
SET
  armor = 123
WHERE entry = 21349;

-- 21621 Cloak of the Golden Hive
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 13,
  stat_value3 = 10,
  stat_value4 = 9
WHERE entry = 21621;

-- 21680 Vest of Swift Execution
UPDATE item_template
SET
  armor = 229
WHERE entry = 21680;

-- 821269 Blessed Qiraji Bulwark Copy
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 15,
  stat_value3 = 13,
  stat_value4 = 30
WHERE entry = 821269;

-- 821270 Blessed Qiraji Bulwark Copy
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 15,
  stat_value3 = 13,
  stat_value4 = 30
WHERE entry = 821270;

-- 821271 Blessed Qiraji Bulwark Copy
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 15,
  stat_value3 = 13,
  stat_value4 = 30
WHERE entry = 821271;

-- 821272 Blessed Qiraji Bulwark Copy
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 15,
  stat_value3 = 13,
  stat_value4 = 30
WHERE entry = 821272;

-- 21336 Doomcaller's Trousers
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 9,
  stat_value3 = 28,
  stat_value4 = 14,
  stat_value5 = 34
WHERE entry = 21336;

-- 21337 Doomcaller's Circlet
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 6,
  stat_value3 = 27,
  stat_value4 = 8,
  stat_value5 = 14,
  stat_value6 = 33
WHERE entry = 21337;

-- 21347 Enigma Circlet
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 12,
  stat_value3 = 24,
  stat_value4 = 8,
  stat_value5 = 14,
  stat_value6 = 33
WHERE entry = 21347;

-- 21348 Tiara of the Oracle
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 16,
  stat_value3 = 22,
  stat_value4 = 8,
  stat_value5 = 28,
  stat_value6 = 9,
  armor = 164
WHERE entry = 21348;

-- 21600 Boots of Epiphany
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 18,
  stat_value3 = 34
WHERE entry = 21600;

-- 21605 Gloves of the Hidden Temple
UPDATE item_template
SET
  armor = 248
WHERE entry = 21605;

-- 21613 Wormhide Boots
UPDATE item_template
SET
  stat_value1 = 32,
  stat_value2 = 36,
  stat_value3 = 13
WHERE entry = 21613;

-- 22815 Severance
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 43,
  stat_value3 = 28
WHERE entry = 22815;

-- 19375 Mish'undare, Circlet of the Mind Flayer
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 9,
  stat_value3 = 15,
  stat_value4 = 28,
  stat_value5 = 35
WHERE entry = 19375;

-- 19381 Boots of the Shadow Flame
UPDATE item_template
SET
  armor = 286
WHERE entry = 19381;

-- 22983 Rime Covered Mantle
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 14,
  stat_value4 = 39
WHERE entry = 22983;

-- 23073 Boots of Displacement
UPDATE item_template
SET
  stat_value1 = 33,
  stat_value2 = 21
WHERE entry = 23073;

-- 23226 Ghoul Skin Tunic
UPDATE item_template
SET
  armor = 411
WHERE entry = 23226;

-- 23038 Band of Unnatural Forces
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 14,
  stat_value3 = 52
WHERE entry = 23038;

-- 832798 Paladin 2h Mace Copy
UPDATE item_template
SET
  stat_value1 = 46,
  stat_value2 = 20
WHERE entry = 832798;

-- 832799 Paladin 2h Mace Copy
UPDATE item_template
SET
  stat_value1 = 46,
  stat_value2 = 20
WHERE entry = 832799;

-- 832800 Paladin 2h Mace Copy
UPDATE item_template
SET
  stat_value1 = 46,
  stat_value2 = 20
WHERE entry = 832800;

-- 23043 The Face of Death
UPDATE item_template
SET
  armor = 3494
WHERE entry = 23043;

-- 31820 Blessed Signet Ring
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12,
  stat_value3 = 12,
  stat_value4 = 12
WHERE entry = 31820;

-- 32647 Shard-bound Bracers
UPDATE item_template
SET
  armor = 146
WHERE entry = 32647;

-- 31282 Shroud of Spiritual Purity
UPDATE item_template
SET
  stat_value1 = 30,
  stat_value2 = 32,
  stat_value3 = 36
WHERE entry = 31282;

-- 30258 Chestplate of A'dal
UPDATE item_template
SET
  stat_value1 = 35,
  stat_value2 = 25,
  stat_value3 = 22,
  stat_value4 = 27
WHERE entry = 30258;

-- 30377 Karja's Medallion
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10,
  stat_value3 = 29
WHERE entry = 30377;

-- 25682 Stylin' Jungle Hat
UPDATE item_template
SET
  stat_value1 = 48,
  stat_value2 = 24,
  stat_value3 = 24,
  stat_value4 = 24,
  stat_value5 = 19,
  stat_value6 = 13
WHERE entry = 25682;

-- 27784 Scintillating Coral Band
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 15,
  stat_value3 = 17,
  stat_value4 = 21
WHERE entry = 27784;

-- 24110 Living Ruby Pendant
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 24,
  stat_value3 = 19,
  stat_value4 = 8
WHERE entry = 24110;

-- 24089 Blazing Eternium Band
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 27,
  stat_value3 = 10
WHERE entry = 24089;

-- 27468 Moonglade Handwraps
UPDATE item_template
SET
  stat_value1 = 38,
  stat_value2 = 13,
  stat_value3 = 18,
  stat_value4 = 20,
  stat_value5 = 17,
  stat_value6 = 21
WHERE entry = 27468;

-- 27491 Signet of Repose
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 18,
  stat_value3 = 20,
  stat_value4 = 14
WHERE entry = 27491;

-- 27537 Gloves of Oblivion
UPDATE item_template
SET
  stat_value1 = 33,
  stat_value2 = 21,
  stat_value3 = 20,
  stat_value4 = 26
WHERE entry = 27537;

-- 27903 Sonic Spear
UPDATE item_template
SET
  stat_value1 = 35,
  stat_value2 = 30,
  stat_value3 = 24
WHERE entry = 27903;

-- 27913 Whispering Blade of Slaying
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 15
WHERE entry = 27913;

-- 28189 Latro's Shifting Sword
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 14
WHERE entry = 28189;

-- 28202 Moonglade Robe
UPDATE item_template
SET
  stat_value1 = 50,
  stat_value2 = 16,
  stat_value3 = 17,
  stat_value4 = 14,
  stat_value5 = 17,
  stat_value6 = 29
WHERE entry = 28202;

-- 28226 Timeslicer
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 15
WHERE entry = 28226;

-- 28252 Bloodfyre Robes of Annihilation
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 27,
  stat_value3 = 54
WHERE entry = 28252;

-- 28263 Stellaris
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 12
WHERE entry = 28263;

-- 28293 High Warlord's Claymore
UPDATE item_template
SET
  stat_value1 = 42,
  stat_value2 = 28,
  stat_value3 = 19,
  stat_value4 = 28,
  stat_value5 = 18
WHERE entry = 28293;

-- 28394 Ryngo's Band of Ingenuity
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 14,
  stat_value3 = 14,
  stat_value4 = 25
WHERE entry = 28394;

-- 28618 Grand Marshal's Dragonhide Gloves
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 34,
  stat_value3 = 11,
  stat_value4 = 17,
  stat_value5 = 16,
  stat_value6 = 19,
  armor = 213
WHERE entry = 28618;

-- 28719 Grand Marshal's Wyrmhide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 28719;

-- 28721 Grand Marshal's Wyrmhide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 28721;

-- 28811 High Warlord's Dragonhide Gloves
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 34,
  stat_value3 = 12,
  stat_value4 = 17,
  stat_value5 = 16,
  stat_value6 = 19,
  armor = 213
WHERE entry = 28811;

-- 28871 High Warlord's Wyrmhide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 28871;

-- 28873 High Warlord's Wyrmhide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 28873;

-- 28917 High Warlord's Bonegrinder
UPDATE item_template
SET
  stat_value1 = 42,
  stat_value2 = 28,
  stat_value3 = 28,
  stat_value4 = 19,
  stat_value5 = 18
WHERE entry = 28917;

-- 28942 Grand Marshal's Bonegrinder
UPDATE item_template
SET
  stat_value1 = 42,
  stat_value2 = 28,
  stat_value3 = 28,
  stat_value4 = 19,
  stat_value5 = 18
WHERE entry = 28942;

-- 28943 Grand Marshal's Warblade
UPDATE item_template
SET
  stat_value1 = 42,
  stat_value2 = 28,
  stat_value3 = 19,
  stat_value4 = 28,
  stat_value5 = 18
WHERE entry = 28943;

-- 29288 Violet Signet
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 18,
  stat_value3 = 12,
  stat_value4 = 22
WHERE entry = 29288;

-- 29329 Terokk's Quill
UPDATE item_template
SET
  stat_value1 = 54,
  stat_value2 = 33
WHERE entry = 29329;

-- 31584 High Warlord's Kodohide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 31584;

-- 31586 High Warlord's Kodohide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 31586;

-- 31589 Grand Marshal's Kodohide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 31589;

-- 31591 Grand Marshal's Kodohide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 31591;

-- 34794 Axe of Shattered Dreams
UPDATE item_template
SET
  stat_value1 = 48,
  stat_value3 = 32
WHERE entry = 34794;

-- 35356 Dragonhide Gloves
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 34,
  stat_value3 = 12,
  stat_value4 = 17,
  stat_value5 = 16,
  stat_value6 = 19,
  armor = 213
WHERE entry = 35356;

-- 35361 Kodohide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 35361;

-- 35363 Kodohide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 35363;

-- 35371 Wyrmhide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 35371;

-- 35373 Wyrmhide Legguards
UPDATE item_template
SET
  armor = 306
WHERE entry = 35373;

-- 35471 Wyrmhide Gloves
UPDATE item_template
SET
  armor = 213
WHERE entry = 35471;

-- 33515 Unwavering Legguards
UPDATE item_template
SET
  stat_value1 = 73,
  stat_value2 = 22,
  stat_value3 = 30,
  stat_value4 = 117
WHERE entry = 33515;

-- 34678 Shattered Sun Pendant of Acumen
UPDATE item_template
SET
  stat_value1 = 26,
  stat_value2 = 22,
  stat_value3 = 42
WHERE entry = 34678;

-- 32017 Merciless Gladiator's Mooncloth Leggings
UPDATE item_template
SET
  armor = 410
WHERE entry = 32017;

-- 32019 Merciless Gladiator's Mooncloth Robe
UPDATE item_template
SET
  armor = 438
WHERE entry = 32019;

-- 29992 Royal Cloak of the Sunstriders
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 22,
  stat_value3 = 44
WHERE entry = 29992;

-- 35870 Stoneground Cleaver
UPDATE item_template
SET
  stat_value1 = 61
WHERE entry = 35870;

-- 34925 Adorned Supernal Legwraps
UPDATE item_template
SET
  armor = 207
WHERE entry = 34925;

-- 34938 Enslaved Doomguard Soulgrips
UPDATE item_template
SET
  armor = 148
WHERE entry = 34938;

-- 38436 Frostscale Bracers
UPDATE item_template
SET
  stat_value1 = 48,
  stat_value2 = 23,
  stat_value3 = 24,
  stat_value4 = 15
WHERE entry = 38436;

-- 30913 Robes of Rhonin
UPDATE item_template
SET
  armor = 253
WHERE entry = 30913;

-- 32525 Cowl of the Illidari High Lord
UPDATE item_template
SET
  armor = 205
WHERE entry = 32525;

-- 34233 Robes of Faltered Light
UPDATE item_template
SET
  armor = 257
WHERE entry = 34233;

-- 37649 Quarry Chisel
UPDATE item_template
SET
  stat_value1 = 48,
  stat_value2 = 33
WHERE entry = 37649;

-- 37697 Trade District Knife
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 58,
  stat_value3 = 33
WHERE entry = 37697;

-- 37856 Librarian's Paper Cutter
UPDATE item_template
SET
  stat_value1 = 46,
  stat_value2 = 26,
  stat_value3 = 25
WHERE entry = 37856;

-- 39221 Wraith Spear
UPDATE item_template
SET
  stat_value1 = 90,
  stat_value2 = 79,
  stat_value3 = 68,
  stat_value4 = 45
WHERE entry = 39221;

-- 39276 The Skull of Ruin
UPDATE item_template
SET
  stat_value1 = 50,
  stat_value2 = 75,
  stat_value3 = 27,
  stat_value4 = 25,
  stat_value5 = 75
WHERE entry = 39276;

-- 40702 Rolfsen's Ripper
UPDATE item_template
SET
  stat_value1 = 39,
  stat_value2 = 50
WHERE entry = 40702;

-- 40704 Pride
UPDATE item_template
SET
  stat_value1 = 39,
  stat_value2 = 50
WHERE entry = 40704;

-- 44308 Signet of Edward the Odd
UPDATE item_template
SET
  stat_value1 = 49,
  stat_value2 = 54,
  stat_value3 = 58,
  stat_value4 = 29
WHERE entry = 44308;

-- 49120 Direbrew's Bloody Shanker
UPDATE item_template
SET
  stat_value2 = 38,
  stat_value3 = 38,
  stat_value4 = 27,
  stat_value5 = 22
WHERE entry = 49120;

-- 40233 The Undeath Carrier
UPDATE item_template
SET
  stat_value2 = 100,
  stat_value3 = 151,
  stat_value4 = 51
WHERE entry = 40233;

-- 41081 Furious Gladiator's Linked Armor
UPDATE item_template
SET
  stat_value1 = 130,
  stat_value2 = 80,
  stat_value3 = 138,
  stat_value4 = 60,
  stat_value5 = 64,
  stat_value6 = 80
WHERE entry = 41081;

-- 41087 Furious Gladiator's Chain Armor
UPDATE item_template
SET
  stat_value1 = 130,
  stat_value2 = 80,
  stat_value3 = 138,
  stat_value4 = 60,
  stat_value5 = 64,
  stat_value6 = 80
WHERE entry = 41087;

-- 41199 Furious Gladiator's Linked Leggings
UPDATE item_template
SET
  stat_value1 = 128,
  stat_value2 = 81,
  stat_value3 = 138,
  stat_value4 = 60,
  stat_value5 = 64,
  stat_value6 = 80
WHERE entry = 41199;

-- 41205 Furious Gladiator's Chain Leggings
UPDATE item_template
SET
  stat_value1 = 128,
  stat_value2 = 81,
  stat_value3 = 138,
  stat_value4 = 60,
  stat_value5 = 64,
  stat_value6 = 80
WHERE entry = 41205;

-- 48445 Wrynn's Legguards of Conquest
UPDATE item_template
SET
  stat_value1 = 92,
  stat_value2 = 157,
  stat_value3 = 80,
  stat_value4 = 45,
  stat_value5 = 240
WHERE entry = 48445;

-- 48459 Hellscream's Legguards of Conquest
UPDATE item_template
SET
  stat_value1 = 92,
  stat_value2 = 157,
  stat_value3 = 80,
  stat_value4 = 45,
  stat_value5 = 240
WHERE entry = 48459;

-- 48635 Turalyon's Legguards of Conquest
UPDATE item_template
SET
  stat_value1 = 92,
  stat_value2 = 157,
  stat_value3 = 80,
  stat_value4 = 45,
  stat_value5 = 240
WHERE entry = 48635;

-- 48655 Liadrin's Legguards of Conquest
UPDATE item_template
SET
  stat_value1 = 92,
  stat_value2 = 157,
  stat_value3 = 80,
  stat_value4 = 45,
  stat_value5 = 240
WHERE entry = 48655;

-- 48983 Titan-Forged Chain Leggings of Triumph
UPDATE item_template
SET
  stat_value1 = 129,
  stat_value2 = 80,
  stat_value3 = 137,
  stat_value4 = 61,
  stat_value5 = 64,
  stat_value6 = 80
WHERE entry = 48983;

-- 49301 Reclaimed Thunderstrike
UPDATE item_template
SET
  stat_value1 = 78,
  stat_value2 = 157,
  stat_value3 = 62,
  stat_value5 = 55
WHERE entry = 49301;

-- 47934 Planestalker Signet
UPDATE item_template
SET
  stat_value1 = 70,
  stat_value2 = 77,
  stat_value3 = 44,
  stat_value4 = 44,
  stat_value5 = 115
WHERE entry = 47934;

-- 48007 Planestalker Band
UPDATE item_template
SET
  stat_value1 = 70,
  stat_value2 = 77,
  stat_value3 = 44,
  stat_value4 = 44,
  stat_value5 = 115
WHERE entry = 48007;

-- 50849 Ymirjar Lord's Handguards
UPDATE item_template
SET
  armor = 2461
WHERE entry = 50849;

-- 50856 Scourgelord Handguards
UPDATE item_template
SET
  armor = 2461
WHERE entry = 50856;

-- 50863 Lightsworn Handguards
UPDATE item_template
SET
  armor = 2461
WHERE entry = 50863;

-- ITEM BUDGET NORMALIZER END
