-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-22T22:16:27
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

-- 1917 Jeweled Dagger
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 11
WHERE entry = 1917;

-- 18957 Brushwood Blade
UPDATE item_template
SET
  dmg_min1 = 11,
  dmg_max1 = 21
WHERE entry = 18957;

-- 816 Small Hand Blade
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 12
WHERE entry = 816;

-- 3223 Frostmane Scepter
UPDATE item_template
SET
  dmg_min1 = 9,
  dmg_max1 = 17
WHERE entry = 3223;

-- 4947 Jagged Dagger
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 12
WHERE entry = 4947;

-- 4948 Stinging Mace
UPDATE item_template
SET
  dmg_min1 = 9,
  dmg_max1 = 18
WHERE entry = 4948;

-- 4303 Cranial Thumper
UPDATE item_template
SET
  dmg_min1 = 12,
  dmg_max1 = 24
WHERE entry = 4303;

-- 4974 Compact Fighting Knife
UPDATE item_template
SET
  dmg_min1 = 6,
  dmg_max1 = 13
WHERE entry = 4974;

-- 3586 Logsplitter
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value2 = 2,
  dmg_min1 = 31,
  dmg_max1 = 47
WHERE entry = 3586;

-- 1405 Foamspittle Staff
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1405;

-- 3154 Thelsamar Axe
UPDATE item_template
SET
  dmg_min1 = 13,
  dmg_max1 = 25
WHERE entry = 3154;

-- 6094 Piercing Axe
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 6094;

-- 6186 Trogg Slicer
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 6186;

-- 15424 Axe of Orgrimmar
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 15424;

-- 3487 Heavy Copper Broadsword
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 3487;

-- 1303 Bridgeworker's Gloves
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 1303;

-- 1314 Ghoul Fingers
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 1314;

-- 1448 Blackrock Gauntlets
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 1448;

-- 2992 Burnished Gloves
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 2992;

-- 5318 Zhovur Axe
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 5318;

-- 5629 Hammerfist Gloves
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 5629;

-- 6477 Grassland Sash
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 6477;

-- 6731 Ironforge Breastplate
UPDATE item_template
SET
  stat_value2 = 3,
  armor = 198
WHERE entry = 6731;

-- 3559 Night Watch Gauntlets
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 3559;

-- 5958 Fine Leather Pants
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 5958;

-- 6333 Spikelash Dagger
UPDATE item_template
SET
  dmg_min1 = 14,
  dmg_max1 = 28
WHERE entry = 6333;

-- 7606 Polar Gauntlets
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 7606;

-- 2175 Shadowhide Battle Axe
UPDATE item_template
SET
  dmg_min1 = 39,
  dmg_max1 = 59
WHERE entry = 2175;

-- 3065 Bright Boots
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 3065;

-- 4445 Flesh Carver
UPDATE item_template
SET
  dmg_min1 = 18,
  dmg_max1 = 35
WHERE entry = 4445;

-- 4800 Mighty Chain Pants
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 4800;

-- 5540 Pearl-handled Dagger
UPDATE item_template
SET
  dmg_min1 = 13,
  dmg_max1 = 26
WHERE entry = 5540;

-- 5749 Scythe Axe
UPDATE item_template
SET
  dmg_min1 = 43,
  dmg_max1 = 66
WHERE entry = 5749;

-- 6191 Kimbra Boots
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 6191;

-- 6481 Dagmire Gauntlets
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 6481;

-- 20425 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 20425;

-- 20434 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 20434;

-- 885 Black Metal Axe
UPDATE item_template
SET
  dmg_min1 = 18,
  dmg_max1 = 34
WHERE entry = 885;

-- 1459 Shadowhide Scalper
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 1459;

-- 1935 Assassin's Blade
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 1935;

-- 2035 Sword of the Night Sky
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 2
WHERE entry = 2035;

-- 3741 Stomping Boots
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 3741;

-- 4706 Lambent Scale Cloak
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 4706;

-- 4793 Sylvan Cloak
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 4793;

-- 4818 Executioner's Sword
UPDATE item_template
SET
  dmg_min1 = 43,
  dmg_max1 = 65
WHERE entry = 4818;

-- 10048 Colorful Kilt
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 5
WHERE entry = 10048;

-- 16890 Slatemetal Cutlass
UPDATE item_template
SET
  stat_value1 = 2,
  stat_value2 = 2
WHERE entry = 16890;

-- 911 Ironwood Treebranch
UPDATE item_template
SET
  stat_value1 = 8
WHERE entry = 911;

-- 1292 Butcher's Cleaver
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1292;

-- 3413 Doomspike
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 3413;

-- 3490 Deadly Bronze Poniard
UPDATE item_template
SET
  dmg_min1 = 16,
  dmg_max1 = 30
WHERE entry = 3490;

-- 3491 Heavy Bronze Mace
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 3491;

-- 15894 Bristlebark Buckler
UPDATE item_template
SET
  stat_value2 = 4
WHERE entry = 15894;

-- 1077 Defias Mage Ring
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 1077;

-- 3056 Forest Leather Pants
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6
WHERE entry = 3056;

-- 3417 Onyx Claymore
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5,
  stat_value3 = 9
WHERE entry = 3417;

-- 4318 Gloves of Meditation
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 4318;

-- 4454 Talon of Vultros
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 4454;

-- 4713 Silver-thread Cloak
UPDATE item_template
SET
  stat_value1 = 4
WHERE entry = 4713;

-- 6318 Odo's Ley Staff
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 5
WHERE entry = 6318;

-- 1276 Fire Hardened Buckler
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 1276;

-- 3069 Bright Robe
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 3069;

-- 3483 Silvered Bronze Gauntlets
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 3483;

-- 4828 Nightwind Belt
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 4828;

-- 6608 Bright Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 6608;

-- 16660 Driftmire Shield
UPDATE item_template
SET
  stat_value1 = 3
WHERE entry = 16660;

-- 2017 Glowing Leather Bracers
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 2017;

-- 3203 Dense Triangle Mace
UPDATE item_template
SET
  dmg_min1 = 44,
  dmg_max1 = 66
WHERE entry = 3203;

-- 6320 Commander's Crest
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value3 = 6
WHERE entry = 6320;

-- 15459 Grimtoll Wristguards
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 15459;

-- 756 Tunnel Pick
UPDATE item_template
SET
  dmg_min1 = 49,
  dmg_max1 = 74
WHERE entry = 756;

-- 897 Madwolf Bracers
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 897;

-- 2014 Black Metal Greatsword
UPDATE item_template
SET
  dmg_min1 = 52,
  dmg_max1 = 78
WHERE entry = 2014;

-- 14400 Resilient Cape
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 14400;

-- 3492 Mighty Iron Hammer
UPDATE item_template
SET
  stat_value1 = 5,
  dmg_min1 = 30,
  dmg_max1 = 57
WHERE entry = 3492;

-- 4051 Emblazoned Boots
UPDATE item_template
SET
  stat_value2 = 3
WHERE entry = 4051;

-- 4837 Strength of Will
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4837;

-- 5770 Robes of Arcana
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 7
WHERE entry = 5770;

-- 6386 Glimmering Mail Legguards
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 7
WHERE entry = 6386;

-- 9535 Fire-welded Bracers
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 9535;

-- 14406 Resilient Cord
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 4
WHERE entry = 14406;

-- 791 Gnarled Ash Staff
UPDATE item_template
SET
  dmg_min1 = 65,
  dmg_max1 = 99
WHERE entry = 791;

-- 4255 Green Leather Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8
WHERE entry = 4255;

-- 6682 Death Speaker Robes
UPDATE item_template
SET
  stat_value2 = 8,
  stat_value3 = 6
WHERE entry = 6682;

-- 7511 Astral Knot Robe
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6,
  stat_value3 = 6
WHERE entry = 7511;

-- 7512 Nether-lace Robe
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6,
  stat_value3 = 6
WHERE entry = 7512;

-- 9515 Nether-lace Tunic
UPDATE item_template
SET
  stat_value2 = 9
WHERE entry = 9515;

-- 9516 Astral Knot Blouse
UPDATE item_template
SET
  stat_value2 = 9
WHERE entry = 9516;

-- 12249 Merciless Axe
UPDATE item_template
SET
  dmg_min1 = 54,
  dmg_max1 = 81
WHERE entry = 12249;

-- 15928 Silver-thread Rod
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 15928;

-- 3849 Hardened Iron Shortsword
UPDATE item_template
SET
  stat_value1 = 5,
  dmg_min1 = 21,
  dmg_max1 = 39
WHERE entry = 3849;

-- 4716 Combat Cloak
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4716;

-- 5820 Faerie Mantle
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6
WHERE entry = 5820;

-- 5962 Guardian Pants
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8
WHERE entry = 5962;

-- 6194 Barreling Reaper
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 6194;

-- 6689 Wind Spirit Staff
UPDATE item_template
SET
  dmg_min1 = 70,
  dmg_max1 = 106
WHERE entry = 6689;

-- 12247 Broad Bladed Knife
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 12247;

-- 14763 Enduring Cape
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 14763;

-- 2953 Watch Master's Cloak
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 2953;

-- 4643 Grimsteel Cape
UPDATE item_template
SET
  stat_value1 = 6
WHERE entry = 4643;

-- 6745 Swiftrunner Cape
UPDATE item_template
SET
  stat_value2 = 6
WHERE entry = 6745;

-- 9699 Garrison Cloak
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 3
WHERE entry = 9699;

-- 14398 Resilient Tunic
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 11
WHERE entry = 14398;

-- 14405 Resilient Robe
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 11
WHERE entry = 14405;

-- 19545 Scout's Blade
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 19545;

-- 19549 Sentinel's Blade
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 19549;

-- 1991 Goblin Power Shovel
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 10
WHERE entry = 1991;

-- 4075 Mail Combat Gauntlets
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 4
WHERE entry = 4075;

-- 14416 Stonecloth Bindings
UPDATE item_template
SET
  stat_value1 = 5
WHERE entry = 14416;

-- 14759 Enduring Bracers
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 6
WHERE entry = 14759;

-- 4054 Insignia Leggings
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 9
WHERE entry = 4054;

-- 5256 Kovork's Rattle
UPDATE item_template
SET
  stat_value2 = 5
WHERE entry = 5256;

-- 6691 Swinetusk Shank
UPDATE item_template
SET
  dmg_min1 = 24,
  dmg_max1 = 45
WHERE entry = 6691;

-- 7687 Ironspine's Fist
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 7687;

-- 15588 Bracesteel Belt
UPDATE item_template
SET
  stat_value2 = 4,
  stat_value3 = 8
WHERE entry = 15588;

-- 18586 Lonetree's Circle
UPDATE item_template
SET
  stat_value2 = 6,
  stat_value3 = 4
WHERE entry = 18586;

-- 1522 Headhunting Spear
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 6
WHERE entry = 1522;

-- 3853 Moonsteel Broadsword
UPDATE item_template
SET
  dmg_min1 = 55,
  dmg_max1 = 83
WHERE entry = 3853;

-- 5009 Mindbender Loop
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 5009;

-- 6694 Heart of Agamaggan
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 7
WHERE entry = 6694;

-- 6784 Braced Handguards
UPDATE item_template
SET
  stat_value2 = 7
WHERE entry = 6784;

-- 9384 Stonevault Shiv
UPDATE item_template
SET
  dmg_min1 = 25,
  dmg_max1 = 47
WHERE entry = 9384;

-- 10358 Duracin Bracers
UPDATE item_template
SET
  stat_value2 = 7
WHERE entry = 10358;

-- 10359 Everlast Boots
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 10359;

-- 14588 Hawkeye's Cord
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 8,
  stat_value3 = 6
WHERE entry = 14588;

-- 1678 Black Ogre Kickers
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 13
WHERE entry = 1678;

-- 1996 Voodoo Band
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 3
WHERE entry = 1996;

-- 2622 Nimar's Tribal Headdress
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 7,
  stat_value3 = 10
WHERE entry = 2622;

-- 4038 Nightsky Robe
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8,
  stat_value3 = 8
WHERE entry = 4038;

-- 4115 Grom'gol Buckler
UPDATE item_template
SET
  stat_value2 = 3,
  stat_value3 = 7
WHERE entry = 4115;

-- 7111 Nightsky Armor
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8,
  stat_value3 = 8
WHERE entry = 7111;

-- 10573 Boneslasher
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 16,
  stat_value3 = 5
WHERE entry = 10573;

-- 14607 Hawkeye's Buckler
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 6
WHERE entry = 14607;

-- 7761 Steelclaw Reaver
UPDATE item_template
SET
  stat_value1 = 3,
  stat_value2 = 8
WHERE entry = 7761;

-- 9718 Reforged Blade of Heroes
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 3,
  dmg_min1 = 31,
  dmg_max1 = 59
WHERE entry = 9718;

-- 15697 Kodo Rustler Boots
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 5
WHERE entry = 15697;

-- 16791 Silkstream Cuffs
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 4
WHERE entry = 16791;

-- 7713 Illusionary Rod
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10,
  stat_value3 = 7
WHERE entry = 7713;

-- 15104 Wingborne Boots
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 15104;

-- 1659 Engineering Gloves
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 8
WHERE entry = 1659;

-- 4329 Star Belt
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 13
WHERE entry = 4329;

-- 8158 Jouster's Gauntlets
UPDATE item_template
SET
  armor = 166
WHERE entry = 8158;

-- 14422 Silksand Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 14422;

-- 14423 Silksand Shoulder Pads
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 14423;

-- 14598 Warden's Waistband
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4,
  stat_value3 = 6
WHERE entry = 14598;

-- 14772 Ravager's Handwraps
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 6
WHERE entry = 14772;

-- 4116 Olmann Sewar
UPDATE item_template
SET
  stat_value1 = 7
WHERE entry = 4116;

-- 4548 Servomechanic Sledgehammer
UPDATE item_template
SET
  dmg_min1 = 53,
  dmg_max1 = 80
WHERE entry = 4548;

-- 9366 Golden Scale Gauntlets
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 4
WHERE entry = 9366;

-- 9424 Ginn-su Sword
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 9424;

-- 9999 Black Mageweave Leggings
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 8
WHERE entry = 9999;

-- 6774 Uthek's Finger
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 5,
  stat_value3 = 5
WHERE entry = 6774;

-- 7941 Heavy Mithril Axe
UPDATE item_template
SET
  stat_value1 = 7,
  dmg_min1 = 45,
  dmg_max1 = 85
WHERE entry = 7941;

-- 9427 Stonevault Bonebreaker
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 4
WHERE entry = 9427;

-- 14421 Silksand Circlet
UPDATE item_template
SET
  stat_value2 = 9,
  stat_value3 = 10
WHERE entry = 14421;

-- 14430 Windchaser Cloak
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 4
WHERE entry = 14430;

-- 1714 Necklace of Calisea
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value3 = 8
WHERE entry = 1714;

-- 4063 Imperial Leather Gloves
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 9
WHERE entry = 4063;

-- 4734 Mistscape Mantle
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 5
WHERE entry = 4734;

-- 9661 Earthclasp Barrier
UPDATE item_template
SET
  armor = 1257
WHERE entry = 9661;

-- 9680 Tok'kar's Murloc Shanker
UPDATE item_template
SET
  dmg_min1 = 28,
  dmg_max1 = 52
WHERE entry = 9680;

-- 19528 Battle Healer's Cloak
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 5,
  stat_value3 = 9
WHERE entry = 19528;

-- 19532 Caretaker's Cape
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 5,
  stat_value3 = 9
WHERE entry = 19532;

-- 20098 Highlander's Cloth Girdle
UPDATE item_template
SET
  armor = 105
WHERE entry = 20098;

-- 20116 Highlander's Leather Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20116;

-- 20166 Defiler's Cloth Girdle
UPDATE item_template
SET
  armor = 105
WHERE entry = 20166;

-- 20192 Defiler's Leather Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20192;

-- 7722 Triune Amulet
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 7,
  stat_value3 = 7
WHERE entry = 7722;

-- 7942 Blue Glittering Axe
UPDATE item_template
SET
  dmg_min1 = 32,
  dmg_max1 = 61
WHERE entry = 7942;

-- 14428 Windchaser Footpads
UPDATE item_template
SET
  stat_value3 = 12
WHERE entry = 14428;

-- 14654 Scorpashi Wristbands
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 6
WHERE entry = 14654;

-- 4080 Blackforge Cowl
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7,
  stat_value3 = 7
WHERE entry = 4080;

-- 4652 Salbac Shield
UPDATE item_template
SET
  stat_value1 = 9
WHERE entry = 4652;

-- 7943 Wicked Mithril Blade
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 4
WHERE entry = 7943;

-- 9359 Wirt's Third Leg
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 4
WHERE entry = 9359;

-- 9411 Rockshard Pauldrons
UPDATE item_template
SET
  stat_value2 = 9,
  stat_value3 = 9
WHERE entry = 9411;

-- 10018 Red Mageweave Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 11
WHERE entry = 10018;

-- 10021 Dreamweave Vest
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 9,
  stat_value3 = 18
WHERE entry = 10021;

-- 10703 Fiendish Skiv
UPDATE item_template
SET
  dmg_min1 = 35,
  dmg_max1 = 66
WHERE entry = 10703;

-- 11856 Ceremonial Elven Blade
UPDATE item_template
SET
  dmg_min1 = 33,
  dmg_max1 = 63
WHERE entry = 11856;

-- 9634 Skilled Handling Gloves
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6,
  stat_value3 = 10
WHERE entry = 9634;

-- 10027 Black Mageweave Shoulders
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 9
WHERE entry = 10027;

-- 12255 Pale Leggings
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12
WHERE entry = 12255;

-- 8110 Hibernal Gloves
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10
WHERE entry = 8110;

-- 8114 Hibernal Sash
UPDATE item_template
SET
  stat_value1 = 4,
  stat_value2 = 13
WHERE entry = 8114;

-- 8121 Heraldic Gloves
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10
WHERE entry = 8121;

-- 20643 Undercity Reservist's Cap
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 11,
  stat_value3 = 10
WHERE entry = 20643;

-- 8216 Big Voodoo Cloak
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 5
WHERE entry = 8216;

-- 9480 Eyegouger
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 10
WHERE entry = 9480;

-- 13018 Executioner's Cleaver
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 10
WHERE entry = 13018;

-- 16738 Witherseed Gloves
UPDATE item_template
SET
  stat_value1 = 13
WHERE entry = 16738;

-- 19039 Zorbin's Water Resistant Hat
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 9,
  stat_value3 = 8
WHERE entry = 19039;

-- 19040 Zorbin's Mega-Slicer
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5
WHERE entry = 19040;

-- 19123 Everwarm Handwraps
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 5
WHERE entry = 19123;

-- 7946 Runed Mithril Hammer
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 4
WHERE entry = 7946;

-- 14779 Khan's Chestpiece
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 10
WHERE entry = 14779;

-- 8131 Myrmidon's Helm
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 11,
  stat_value3 = 14
WHERE entry = 8131;

-- 14441 Venomshroud Mask
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 10
WHERE entry = 14441;

-- 14846 Sunscale Gauntlets
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7,
  stat_value3 = 6
WHERE entry = 14846;

-- 19116 Greenleaf Handwraps
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 12
WHERE entry = 19116;

-- 8282 Valorous Shield
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 9
WHERE entry = 8282;

-- 10652 Will of the Mountain Giant
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 14,
  dmg_min1 = 88,
  dmg_max1 = 133
WHERE entry = 10652;

-- 10742 Dragonflight Leggings
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 6,
  stat_value3 = 14
WHERE entry = 10742;

-- 13085 Horizon Choker
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 4,
  stat_value3 = 4
WHERE entry = 13085;

-- 14662 Keeper's Hooves
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 12,
  stat_value3 = 6
WHERE entry = 14662;

-- 13857 Runecloth Tunic
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 11
WHERE entry = 13857;

-- 13858 Runecloth Robe
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 11
WHERE entry = 13858;

-- 8314 Alabaster Plate Gauntlets
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 14
WHERE entry = 8314;

-- 19567 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 11,
  stat_value3 = 9
WHERE entry = 19567;

-- 19571 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 11,
  stat_value3 = 9
WHERE entry = 19571;

-- 20097 Highlander's Cloth Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20097;

-- 20115 Highlander's Leather Girdle
UPDATE item_template
SET
  armor = 136
WHERE entry = 20115;

-- 20165 Defiler's Cloth Girdle
UPDATE item_template
SET
  armor = 113
WHERE entry = 20165;

-- 20193 Defiler's Leather Girdle
UPDATE item_template
SET
  armor = 136
WHERE entry = 20193;

-- 14437 Venomshroud Vest
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 18
WHERE entry = 14437;

-- 17710 Charstone Dirk
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 3
WHERE entry = 17710;

-- 9649 Royal Highmark Vestments
UPDATE item_template
SET
  stat_value2 = 3,
  stat_value3 = 16
WHERE entry = 9649;

-- 12774 Dawn's Edge
UPDATE item_template
SET
  stat_value1 = 14
WHERE entry = 12774;

-- 13122 Dark Phantom Cape
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 6
WHERE entry = 13122;

-- 14855 Vanguard Gauntlets
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 6,
  stat_value3 = 18
WHERE entry = 14855;

-- 11874 Clouddrift Mantle
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 12
WHERE entry = 11874;

-- 13182 Phase Blade
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 7
WHERE entry = 13182;

-- 22205 Black Steel Bindings
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 14
WHERE entry = 22205;

-- 22256 Mana Shaping Handwraps
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 9,
  stat_value3 = 7,
  stat_value4 = 16
WHERE entry = 22256;

-- 12059 Conqueror's Medallion
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 10,
  stat_value3 = 5,
  stat_value4 = 4
WHERE entry = 12059;

-- 14144 Ghostweave Pants
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 10
WHERE entry = 14144;

-- 18324 Waveslicer
UPDATE item_template
SET
  stat_value1 = 26,
  stat_value2 = 14
WHERE entry = 18324;

-- 12554 Hands of the Exalted Herald
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12,
  stat_value3 = 18
WHERE entry = 12554;

-- 12557 Ebonsteel Spaulders
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 14,
  stat_value3 = 6,
  armor = 553
WHERE entry = 12557;

-- 13101 Wolfrunner Shoes
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 11,
  stat_value3 = 11,
  stat_value4 = 13
WHERE entry = 13101;

-- 13395 Skul's Fingerbone Claws
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 40
WHERE entry = 13395;

-- 14453 Highborne Robes
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15
WHERE entry = 14453;

-- 14455 Highborne Padded Armor
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 15
WHERE entry = 14455;

-- 18536 Milli's Lexicon
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 6,
  stat_value3 = 8
WHERE entry = 18536;

-- 18743 Gracious Cape
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 8
WHERE entry = 18743;

-- ITEM BUDGET NORMALIZER END
