-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-23T08:24:30
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

-- 8308 Hero's Band
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 14,
  stat_value3 = 17
WHERE entry = 8308;

-- 13373 Band of Flesh
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 6,
  stat_value3 = 3
WHERE entry = 13373;

-- 13374 Soulstealer Mantle
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 22
WHERE entry = 13374;

-- 13959 Omokk's Girth Restrainer
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 9,
  stat_value3 = 14
WHERE entry = 13959;

-- 18369 Gordok's Handwraps
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 14
WHERE entry = 18369;

-- 18494 Denwatcher's Shoulders
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 18
WHERE entry = 18494;

-- 18497 Sublime Wristguards
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 6,
  stat_value3 = 6,
  stat_value4 = 12
WHERE entry = 18497;

-- 19095 Frostwolf Legionnaire's Pendant
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 18
WHERE entry = 19095;

-- 19097 Stormpike Soldier's Pendant
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 18
WHERE entry = 19097;

-- 19575 Strength of Mugamba
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 7,
  stat_value3 = 10,
  stat_value4 = 6
WHERE entry = 19575;

-- 20660 Stonecutting Glaive
UPDATE item_template
SET
  stat_value1 = 29,
  stat_value2 = 12
WHERE entry = 20660;

-- 22204 Wristguards of Renown
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 10,
  stat_value3 = 10
WHERE entry = 22204;

-- 18347 Well Balanced Axe
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 18347;

-- 18386 Padre's Trousers
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 22,
  stat_value3 = 8
WHERE entry = 18386;

-- 18680 Ancient Bone Bow
UPDATE item_template
SET
  stat_value1 = 11
WHERE entry = 18680;

-- 18740 Thuzadin Sash
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 11,
  stat_value3 = 11,
  stat_value4 = 11
WHERE entry = 18740;

-- 22319 Tome of Divine Right
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value3 = 14,
  stat_value4 = 5
WHERE entry = 22319;

-- 22322 The Jaw Breaker
UPDATE item_template
SET
  stat_value1 = 14
WHERE entry = 22322;

-- 22472 Boots of Ferocity
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 13,
  stat_value3 = 26
WHERE entry = 22472;

-- 13083 Garrett Family Crest
UPDATE item_template
SET
  stat_value1 = 5,
  stat_value2 = 4,
  stat_value3 = 17
WHERE entry = 13083;

-- 13950 Detention Strap
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 11,
  stat_value3 = 10
WHERE entry = 13950;

-- 16996 Gorewood Bow
UPDATE item_template
SET
  stat_value1 = 9
WHERE entry = 16996;

-- 16998 Sacred Protector
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10
WHERE entry = 16998;

-- 18378 Silvermoon Leggings
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 10,
  stat_value3 = 16,
  stat_value4 = 6,
  stat_value5 = 18
WHERE entry = 18378;

-- 18389 Cloak of the Cosmos
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 7,
  stat_value3 = 14
WHERE entry = 18389;

-- 18507 Boots of the Full Moon
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 9,
  stat_value3 = 12,
  stat_value4 = 14
WHERE entry = 18507;

-- 18686 Bone Golem Shoulders
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 9,
  stat_value3 = 9
WHERE entry = 18686;

-- 18695 Spellbound Tome
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 6,
  stat_value3 = 3
WHERE entry = 18695;

-- 18754 Fel Hardened Bracers
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 5
WHERE entry = 18754;

-- 21179 Band of Earthen Wrath
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 14,
  stat_value3 = 4
WHERE entry = 21179;

-- 12587 Eye of Rend
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 26,
  stat_value3 = 28
WHERE entry = 12587;

-- 13023 Eaglehorn Long Bow
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 13023;

-- 13986 Crown of Caer Darrow
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 20,
  stat_value3 = 8
WHERE entry = 13986;

-- 15411 Mark of Fordring
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 26
WHERE entry = 15411;

-- 18420 Bonecrusher
UPDATE item_template
SET
  stat_value1 = 30,
  stat_value2 = 14
WHERE entry = 18420;

-- 19110 Cold Forged Blade
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 5
WHERE entry = 19110;

-- 19566 Advisor's Gnarled Staff
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 13,
  stat_value3 = 10
WHERE entry = 19566;

-- 19570 Lorekeeper's Staff
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 13,
  stat_value3 = 10
WHERE entry = 19570;

-- 20695 Abyssal War Beads
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 20
WHERE entry = 20695;

-- 20696 Crystal Spiked Maul
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 28
WHERE entry = 20696;

-- 20712 Wastewalker's Gauntlets
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 10,
  stat_value3 = 10,
  stat_value4 = 10,
  stat_value5 = 10
WHERE entry = 20712;

-- 20715 Dunestalker's Boots
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 10,
  stat_value3 = 18
WHERE entry = 20715;

-- 22150 Beads of Ogre Might
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 10,
  stat_value3 = 24
WHERE entry = 22150;

-- 22247 Faith Healer's Boots
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 10,
  stat_value4 = 14
WHERE entry = 22247;

-- 22326 Amalgam's Band
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 5,
  stat_value3 = 14,
  stat_value4 = 4
WHERE entry = 22326;

-- 14456 Elunarian Vest
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 21,
  stat_value3 = 5
WHERE entry = 14456;

-- 14464 Elunarian Silk Robes
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 21,
  stat_value3 = 5
WHERE entry = 14464;

-- 14812 Warstrike Buckler
UPDATE item_template
SET
  stat_value2 = 15
WHERE entry = 14812;

-- 19050 Mantle of the Timbermaw
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 8
WHERE entry = 19050;

-- 17109 Choker of Enlightenment
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 10,
  stat_value3 = 9,
  stat_value4 = 18
WHERE entry = 17109;

-- 18282 Core Marksman Rifle
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 18282;

-- 19944 Nat Pagle's Fish Terminator
UPDATE item_template
SET
  stat_value1 = 41,
  stat_value2 = 19
WHERE entry = 19944;

-- 20032 Flowing Ritual Robes
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 23,
  stat_value3 = 15,
  stat_value4 = 22
WHERE entry = 20032;

-- 19885 Jin'do's Evil Eye
UPDATE item_template
SET
  stat_value1 = 11,
  stat_value2 = 6,
  stat_value3 = 5,
  stat_value4 = 23
WHERE entry = 19885;

-- 19890 Jin'do's Hexxer
UPDATE item_template
SET
  stat_value1 = 9,
  stat_value2 = 6,
  stat_value3 = 14
WHERE entry = 19890;

-- 21183 Earthpower Vest
UPDATE item_template
SET
  stat_value1 = 22,
  stat_value2 = 14,
  stat_value3 = 25
WHERE entry = 21183;

-- 19593 The Eye of Zuldazar
UPDATE item_template
SET
  stat_value1 = 8,
  stat_value2 = 13,
  stat_value3 = 8,
  stat_value4 = 9
WHERE entry = 19593;

-- 19600 Pebble of Kajaro
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 8,
  stat_value3 = 8,
  stat_value4 = 9
WHERE entry = 19600;

-- 19906 Blooddrenched Footpads
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 10,
  stat_value3 = 10
WHERE entry = 19906;

-- 19915 Zulian Defender
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 9,
  stat_value3 = 8
WHERE entry = 19915;

-- 19928 Animist's Spaulders
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 12,
  stat_value3 = 11,
  stat_value4 = 20
WHERE entry = 19928;

-- 19993 Hoodoo Hunting Bow
UPDATE item_template
SET
  stat_value1 = 10
WHERE entry = 19993;

-- 22720 Zulian Headdress
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 14,
  stat_value3 = 13,
  stat_value4 = 29
WHERE entry = 22720;

-- 21466 Stinger of Ayamiss
UPDATE item_template
SET
  stat_value1 = 7,
  stat_value2 = 9,
  stat_value3 = 14
WHERE entry = 21466;

-- 20213 Belt of Shrunken Heads
UPDATE item_template
SET
  stat_value1 = 23,
  stat_value2 = 11,
  stat_value3 = 14
WHERE entry = 20213;

-- 21507 Amulet of the Shifting Sands
UPDATE item_template
SET
  stat_value1 = 25,
  stat_value2 = 8
WHERE entry = 21507;

-- 19869 Blooddrenched Grips
UPDATE item_template
SET
  stat_value1 = 16,
  stat_value2 = 14,
  stat_value3 = 34
WHERE entry = 19869;

-- 19895 Bloodtinged Kilt
UPDATE item_template
SET
  stat_value1 = 20,
  stat_value2 = 20,
  stat_value3 = 28
WHERE entry = 19895;

-- 20632 Mindtear Band
UPDATE item_template
SET
  stat_value1 = 6,
  stat_value2 = 6,
  stat_value3 = 14,
  stat_value4 = 22
WHERE entry = 20632;

-- 19403 Band of Forced Concentration
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 9,
  stat_value3 = 8,
  stat_value4 = 21
WHERE entry = 19403;

-- 21621 Cloak of the Golden Hive
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 13,
  stat_value3 = 10,
  stat_value4 = 9
WHERE entry = 21621;

-- 21600 Boots of Epiphany
UPDATE item_template
SET
  stat_value1 = 19,
  stat_value2 = 18,
  stat_value3 = 34
WHERE entry = 21600;

-- 19375 Mish'undare, Circlet of the Mind Flayer
UPDATE item_template
SET
  stat_value1 = 24,
  stat_value2 = 9,
  stat_value3 = 15,
  stat_value4 = 28,
  stat_value5 = 35
WHERE entry = 19375;

-- 22983 Rime Covered Mantle
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 12,
  stat_value3 = 14,
  stat_value4 = 39
WHERE entry = 22983;

-- 23038 Band of Unnatural Forces
UPDATE item_template
SET
  stat_value1 = 10,
  stat_value2 = 14,
  stat_value3 = 52
WHERE entry = 23038;

-- ITEM BUDGET NORMALIZER END
