-- ITEM BUDGET NORMALIZER BEGIN
-- Generated by tools/item_budget_normalizer/normalize_items.py
-- Date: 2026-06-22T22:16:51
-- Config: C:\AzerothCore\Burning_ Legacy_Server\AzerothCore-wotlk-with-NPCBots\tools\item_budget_normalizer\item_budget_config.yml
-- Dry-run reviewed: no

-- 31820 Blessed Signet Ring
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 12,
  stat_value3 = 12,
  stat_value4 = 12
WHERE entry = 31820;

-- 32647 Shard-bound Bracers
UPDATE item_template
SET
  armor = 146
WHERE entry = 32647;

-- 31282 Shroud of Spiritual Purity
UPDATE item_template
SET
  stat_value1 = 30,
  stat_value2 = 32,
  stat_value3 = 36
WHERE entry = 31282;

-- 30369 Cleansed Fel Pauldrons
UPDATE item_template
SET
  stat_value1 = 68,
  stat_value2 = 18,
  stat_value3 = 21
WHERE entry = 30369;

-- 30377 Karja's Medallion
UPDATE item_template
SET
  stat_value1 = 15,
  stat_value2 = 10,
  stat_value3 = 29
WHERE entry = 30377;

-- 27784 Scintillating Coral Band
UPDATE item_template
SET
  stat_value1 = 14,
  stat_value2 = 15,
  stat_value3 = 17,
  stat_value4 = 21
WHERE entry = 27784;

-- 31291 Crystalforged War Axe
UPDATE item_template
SET
  stat_value1 = 50,
  stat_value2 = 27
WHERE entry = 31291;

-- 24089 Blazing Eternium Band
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 27,
  stat_value3 = 10
WHERE entry = 24089;

-- 27491 Signet of Repose
UPDATE item_template
SET
  stat_value1 = 17,
  stat_value2 = 18,
  stat_value3 = 20,
  stat_value4 = 14
WHERE entry = 27491;

-- 27903 Sonic Spear
UPDATE item_template
SET
  stat_value1 = 35,
  stat_value2 = 30,
  stat_value3 = 24
WHERE entry = 27903;

-- 27913 Whispering Blade of Slaying
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 15
WHERE entry = 27913;

-- 28226 Timeslicer
UPDATE item_template
SET
  stat_value1 = 13,
  stat_value2 = 15
WHERE entry = 28226;

-- 28252 Bloodfyre Robes of Annihilation
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 27,
  stat_value3 = 54
WHERE entry = 28252;

-- 28263 Stellaris
UPDATE item_template
SET
  stat_value1 = 21,
  stat_value2 = 12
WHERE entry = 28263;

-- 28394 Ryngo's Band of Ingenuity
UPDATE item_template
SET
  stat_value1 = 12,
  stat_value2 = 14,
  stat_value3 = 14,
  stat_value4 = 25
WHERE entry = 28394;

-- 29288 Violet Signet
UPDATE item_template
SET
  stat_value1 = 18,
  stat_value2 = 18,
  stat_value3 = 12,
  stat_value4 = 22
WHERE entry = 29288;

-- 29329 Terokk's Quill
UPDATE item_template
SET
  stat_value1 = 54,
  stat_value2 = 33
WHERE entry = 29329;

-- 33515 Unwavering Legguards
UPDATE item_template
SET
  stat_value1 = 73,
  stat_value2 = 22,
  stat_value3 = 30,
  stat_value4 = 117
WHERE entry = 33515;

-- 29992 Royal Cloak of the Sunstriders
UPDATE item_template
SET
  stat_value1 = 27,
  stat_value2 = 22,
  stat_value3 = 44
WHERE entry = 29992;

-- ITEM BUDGET NORMALIZER END
